<a href="https://colab.research.google.com/github/migueromrto-lab/repository/blob/main/Cleaning_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import glob
import os
from functools import reduce

# Ruta a tu carpeta con excels en Drive
ruta = "/content/drive/MyDrive/DATOS FBREF 5 GRANDES LIGAS"

# Obtener lista de archivos .xlsx
archivos = glob.glob(os.path.join(ruta, "*.xlsx"))
print("Archivos encontrados:", archivos)

Archivos encontrados: ['/content/drive/MyDrive/DATOS FBREF 5 GRANDES LIGAS/POSESIÓN 90 5GL (CHECK).xlsx', '/content/drive/MyDrive/DATOS FBREF 5 GRANDES LIGAS/TIROS 5 GL (CHECK).xlsx', '/content/drive/MyDrive/DATOS FBREF 5 GRANDES LIGAS/A. DEFENSIVAS 90 5GL (CHECK).xlsx', '/content/drive/MyDrive/DATOS FBREF 5 GRANDES LIGAS/TIPOS DE PASES 90 5GL (check) orden incorrecto .xlsx', '/content/drive/MyDrive/DATOS FBREF 5 GRANDES LIGAS/PASES  90 TOP 5L (CHECK) .xlsx', '/content/drive/MyDrive/DATOS FBREF 5 GRANDES LIGAS/Misceláneas TOP5 (CHECK).xlsx', '/content/drive/MyDrive/DATOS FBREF 5 GRANDES LIGAS/CREACIÓN GOLES TIROS 5 GL (CHECK).xlsx']

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
dataframes = []

# Establece columnas clave comunes a todos los excels
columnas_clave = ['Jugador', 'País', 'Posc', 'Equipo', 'Comp', 'Nacimiento']

for archivo in archivos:
    df = pd.read_excel(archivo)

    # Eliminar columnas duplicadas (por ejemplo 'Rk' si existe)
    if 'Rk' in df.columns:
        df = df.drop(columns=['Rk'])

    # Asegurarse de que las columnas clave están
    columnas_presentes = [col for col in columnas_clave if col in df.columns]
    df = df.set_index(columnas_presentes)

    # Añadir al listado
    dataframes.append(df)

# Unir horizontalmente por las claves comunes
df_final = pd.concat(dataframes, axis=1).reset_index()

# Eliminar columnas duplicadas si aparecen
df_final = df_final.loc[:, ~df_final.columns.duplicated()]

In [ ]:
df_final.head()

,Jugador,País,Posc,Equipo,Comp,Nacimiento,Edad,90 s,Toques,TDef. pen.,T3.º def.,T3.º cent.,T3.º ataq.,TAtaq. pen.,TBalón vivo,RegAtt,RegSucc,RegSucc%,Tkld,Tkld%,Participaciones con balón,Dist. tot. Conducc,Dist. prg. conducc,PrgConducc,Conducc1/3,ConducArea,Errores de control,Tackle exit. recibidos,PasesRec,PasesPrgRec,Gls,Tiros,TirosAP,% de TirosAP,T/90,TirosaAP/90,G/T,G/TirosAP,DistTiros,TirosFK,Gol Penalti,Penaltis lanzados,xG,xG/90,npxG,npxG/90,npxG/Sh,G-xG,np:G-xG,Tkl,TklG,tkl3.º def.,tkl3.º cent.,tkl3.º ataq.,RegTkl,AttRegTkl,Tkl%,DesafPerd,Bloqueos,DisBloq,PasesBloq,Intercepciones,Tkl+Int,Despejes,Errores def tiro,Pases balón vivo,Pases balón muerto,Pases de TL,Pases largos,Cambios,Centros,Lanzamientos,Corners,Corners Dentro,Corneres Fuera,Corners recto,Pases FDJ,Pases bloqueados,PasesCompletados,PasesInt.,PasesFallados,% Pases,Dist. Pase. tot.,Dist. pase prg.,PaseCortCmp,PaseCortInt.,PaseCortFallados,% PaseCortCmp,PaseMedCmp,PMedInt.,PaseMedFallados,% PaseMedCmp,PaseLarCmp,PaseLarInt.,PaseLargFallados,%PaseLarCmp,Asist,xAG,xA,A-xAG,PClave,Pas3ºAtaq,PasAreaPen,CentrosArea,PasesPrg,TA,TR,2a amarilla,Faltas,FaltasRec,FDJ,Penal ejecutado,Penal concedido,GolesPP,Recuperaciones,Aéreos Totales,AéreeosGanados,AéreosPerdidos,% de aéreos ganados,Acciones creación tiros,Pases que acaban en tiro,Pases balón muerto llevan a tiro,Regates llevan a tiro,TirosReboteTiro,Faltas rec. llevan a tiro,Acc. def. llevan a tiro,Acciones creación Goles,Pases llevan a gol,Pases balón vivo gol,Pases balón muerto gol,Regates llevan a gol,TirosReboteGol,Faltas rec. llevan a gol,Acc. def llevan a gol
0,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,2000.0,25-130,1.0,73.0,2.00,19.0,40.0,15.0,0.00,73.0,2.00,0.00,0.0,1.00,50.0,41.0,152.0,68.0,1.00,0.00,0.00,1.00,0.00,40.0,3.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.00,0.0,0.0,2.00,2.00,1.00,1.00,0.0,1.00,1.00,100.0,0.0,3.00,1.0,2.00,1.00,3.00,0.0,0.0,51.0,12.00,2.0,0.0,0.0,2.00,10.00,0.0,0.0,0.0,0.0,0.0,1.00,50.0,63.0,13.0,79.4,887.0,361.0,21.0,25.0,4.0,84.0,24.00,29.0,5.00,82.8,4.00,7.00,3.00,57.1,0.0,0.0,0.0,0.0,0.00,8.00,0.0,0.0,8.00,0.00,0.0,0.0,0.00,2.00,0.00,0.0,0.0,0.0,7.00,0.00,0.00,0.00,NaN,2,"2,09","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
1,Max Aarons,eng ENG,"DF,CC",Valencia,es La Liga,2000.0,25-130,1.2,49.2,0.83,14.2,10.0,25.0,0.00,49.2,3.33,0.83,25.0,1.67,50.0,25.0,79.2,34.2,0.00,2.50,0.00,1.67,0.83,27.5,6.67,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.00,0.0,0.0,2.50,2.50,1.67,0.83,0.0,2.50,2.50,100.0,0.0,0.83,0.0,0.83,0.00,2.50,2.5,0.0,29.2,5.83,0.0,0.0,0.0,1.67,5.83,0.0,0.0,0.0,0.0,0.0,0.83,24.2,35.0,10.8,69.0,345.0,108.3,13.3,18.3,5.0,72.7,9.17,13.3,4.13,68.8,0.83,1.67,0.84,50.0,0.0,0.0,0.0,0.0,0.83,0.83,0.0,0.0,3.33,1.54,0.0,0.0,0.00,1.54,0.00,0.0,0.0,0.0,5.38,2.31,1.54,0.77,66.7,"0,83","0,87","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
2,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,2003.0,22-002,0.7,51.4,1.43,11.4,27.1,12.9,1.43,51.4,1.43,1.43,100.0,0.00,0.0,18.6,144.3,95.7,4.29,2.86,1.43,0.00,2.86,22.9,4.29,0.0,1.0,0.0,0.0,1.38,0.0,0.0,0.0,24.5,0.0,0.0,0.0,0.1,0.142857,0.1,0.142857,0.07,-0.1,-0.1,4.29,2.86,2.86,1.43,0.0,4.29,4.29,100.0,0.0,1.43,0.0,1.43,1.43,5.71,0.0,0.0,30.0,11.40,0.0,0.0,0.0,1.43,11.40,0.0,0.0,0.0,0.0,0.0,2.86,24.3,41.4,17.1,58.6,382.9,157.1,15.7,20.0,4.3,78.6,5.71,10.0,4.29,57.1,2.86,10.00,7.14,28.6,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,2.86,1.43,0.0,0.0,2.86,0.00,1.43,0.0,0.0,0.0,2.86,1.43,0.00,1.43,0.0,0,0,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
3,James Abankwah,ie IRL,"DF,CC",Udinese,it Serie A,2004.0,21-118,1.0,65.0,8.00,37.0,22.0,7.0,2.00,65.0,0.00,0.00,NaN,0.00,NaN,29.0,219.0,165.0,3.00,1.00,1.00,1.00,3.00,34.0,1.00,0.0,1.0,0.0,0.0,1.02,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.1,0.1,0.1,0.1,0.06,-0.1,-0.1,4.00,2.00,4.00,0.00,0.0,2.00,3.00,66.7,1.0,2.00,1.0,1.00,1.00,5.00,3.0,0.0,45.0,1.00,1.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00,36.0,46.0,10.0,78.3,614.0,206.0,13.0,15.0,2.0,86.7,18.00,21.0,3.00,85.7,3.00,8.00,5.00,37.5,0.0,0.0,0.0,0.0,0.00,2.00,0.0,0.0,4.00,1.00,0.0,0.0,4.00,3.00,0.00,0.0,0.0,0.0,7.00,4.00,2.00,2.00,50.0,1,"1,02","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
4,Keyliane Abdallah,fr FRA,DL,Marseille,fr Ligue 1,2006.0,19-039,0.0,4.0,0.00,3.0,1.0,0.0,0.00,4.0,0.00,0.00,NaN,0.00,NaN,1.0,10.0,9.0,1.00,0.00,0.00,1.00,0.00,3.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,#DIV/0!,0.0,#DIV/0!,0.00,0.0,0.0,1.00,1.00,1.00,NaN,NaN,1.00,1.00,100.0,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2.0,0.00,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00,2.0,2.0,0.0,100.0,41.0,0.0,0.0,0.0,0.0,NaN,2.00,2.0,0.00,100.0,0.00,0.00,0.00,NaN,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,NaN,0,0,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"

In [ ]:
df=df_final

In [ ]:
df = df.fillna(0)

In [ ]:
# prompt: en la columna "Nacimiento", quitar los decimales. Solo numeros enteros

df['Nacimiento'] = df['Nacimiento'].astype(int)

In [ ]:
#Función para limpiar duplicados y eliminar jugadores sin participación

def Limpiar_duplicados(df):
    df = df.copy()

    # Ordenar por jugador y 90s (de mayor a menor)
    df = df.sort_values(by=["Jugador", "90 s"], ascending=[True, False])

    # Contar ocurrencias acumuladas de cada jugador
    df['duplicado_n'] = df.groupby('Jugador').cumcount()

    # Añadir sufijo solo si es una ocurrencia duplicada (i.e., n > 0)
    df.loc[df['duplicado_n'] > 0, 'Jugador'] = df['Jugador'] + '_' + (df['duplicado_n'] + 1).astype(str)

    # Eliminar la columna auxiliar
    df.drop(columns='duplicado_n', inplace=True)

    # Limpiar espacios y convertir a numérico
    df['90 s'] = df['90 s'].astype(str).str.strip()
    df['90 s'] = pd.to_numeric(df['90 s'], errors='coerce')

    # Eliminar jugadores sin participación
    df = df[df['90 s'] != 0.0]

    # Reordenar por índice
    df = df.sort_index()

    return df

In [ ]:
df = Limpiar_duplicados(df)

In [ ]:
df.head()

,Jugador,País,Posc,Equipo,Comp,Nacimiento,Edad,90 s,Toques,TDef. pen.,T3.º def.,T3.º cent.,T3.º ataq.,TAtaq. pen.,TBalón vivo,RegAtt,RegSucc,RegSucc%,Tkld,Tkld%,Participaciones con balón,Dist. tot. Conducc,Dist. prg. conducc,PrgConducc,Conducc1/3,ConducArea,Errores de control,Tackle exit. recibidos,PasesRec,PasesPrgRec,Gls,Tiros,TirosAP,% de TirosAP,T/90,TirosaAP/90,G/T,G/TirosAP,DistTiros,TirosFK,Gol Penalti,Penaltis lanzados,xG,xG/90,npxG,npxG/90,npxG/Sh,G-xG,np:G-xG,Tkl,TklG,tkl3.º def.,tkl3.º cent.,tkl3.º ataq.,RegTkl,AttRegTkl,Tkl%,DesafPerd,Bloqueos,DisBloq,PasesBloq,Intercepciones,Tkl+Int,Despejes,Errores def tiro,Pases balón vivo,Pases balón muerto,Pases de TL,Pases largos,Cambios,Centros,Lanzamientos,Corners,Corners Dentro,Corneres Fuera,Corners recto,Pases FDJ,Pases bloqueados,PasesCompletados,PasesInt.,PasesFallados,% Pases,Dist. Pase. tot.,Dist. pase prg.,PaseCortCmp,PaseCortInt.,PaseCortFallados,% PaseCortCmp,PaseMedCmp,PMedInt.,PaseMedFallados,% PaseMedCmp,PaseLarCmp,PaseLarInt.,PaseLargFallados,%PaseLarCmp,Asist,xAG,xA,A-xAG,PClave,Pas3ºAtaq,PasAreaPen,CentrosArea,PasesPrg,TA,TR,2a amarilla,Faltas,FaltasRec,FDJ,Penal ejecutado,Penal concedido,GolesPP,Recuperaciones,Aéreos Totales,AéreeosGanados,AéreosPerdidos,% de aéreos ganados,Acciones creación tiros,Pases que acaban en tiro,Pases balón muerto llevan a tiro,Regates llevan a tiro,TirosReboteTiro,Faltas rec. llevan a tiro,Acc. def. llevan a tiro,Acciones creación Goles,Pases llevan a gol,Pases balón vivo gol,Pases balón muerto gol,Regates llevan a gol,TirosReboteGol,Faltas rec. llevan a gol,Acc. def llevan a gol
0,Max Aarons_2,eng ENG,DF,Bournemouth,eng Premier League,2000,25-130,1.0,73.0,2.00,19.0,40.0,15.00,0.00,73.0,2.00,0.00,0.0,1.00,50.0,41.0,152.0,68.0,1.00,0.00,0.00,1.00,0.00,40.0,3.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.00,0.0,0.0,2.00,2.00,1.00,1.00,0.0,1.00,1.00,100.0,0.00,3.00,1.00,2.00,1.00,3.00,0.00,0.00,51.0,12.00,2.00,0.0,0.0,2.00,10.00,0.0,0.0,0.0,0.0,0.00,1.00,50.0,63.0,13.0,79.4,887.0,361.0,21.0,25.0,4.0,84.0,24.00,29.0,5.00,82.8,4.00,7.00,3.00,57.1,0.0,0.00,0.00,0.00,0.00,8.00,0.0,0.0,8.00,0.00,0.0,0.0,0.00,2.00,0.00,0.0,0.0,0.0,7.00,0.00,0.00,0.00,0.0,2,"2,09","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
1,Max Aarons,eng ENG,"DF,CC",Valencia,es La Liga,2000,25-130,1.2,49.2,0.83,14.2,10.0,25.00,0.00,49.2,3.33,0.83,25.0,1.67,50.0,25.0,79.2,34.2,0.00,2.50,0.00,1.67,0.83,27.5,6.67,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.00,0.0,0.0,2.50,2.50,1.67,0.83,0.0,2.50,2.50,100.0,0.00,0.83,0.00,0.83,0.00,2.50,2.50,0.00,29.2,5.83,0.00,0.0,0.0,1.67,5.83,0.0,0.0,0.0,0.0,0.00,0.83,24.2,35.0,10.8,69.0,345.0,108.3,13.3,18.3,5.0,72.7,9.17,13.3,4.13,68.8,0.83,1.67,0.84,50.0,0.0,0.00,0.00,0.00,0.83,0.83,0.0,0.0,3.33,1.54,0.0,0.0,0.00,1.54,0.00,0.0,0.0,0.0,5.38,2.31,1.54,0.77,66.7,"0,83","0,87","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
2,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,2003,22-002,0.7,51.4,1.43,11.4,27.1,12.90,1.43,51.4,1.43,1.43,100.0,0.00,0.0,18.6,144.3,95.7,4.29,2.86,1.43,0.00,2.86,22.9,4.29,0.0,1.0,0.0,0.0,1.38,0.00,0.0,0.0,24.5,0.0,0.0,0.0,0.1,0.142857,0.1,0.142857,0.07,-0.1,-0.1,4.29,2.86,2.86,1.43,0.0,4.29,4.29,100.0,0.00,1.43,0.00,1.43,1.43,5.71,0.00,0.00,30.0,11.40,0.00,0.0,0.0,1.43,11.40,0.0,0.0,0.0,0.0,0.00,2.86,24.3,41.4,17.1,58.6,382.9,157.1,15.7,20.0,4.3,78.6,5.71,10.0,4.29,57.1,2.86,10.00,7.14,28.6,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0,2.86,1.43,0.0,0.0,2.86,0.00,1.43,0.0,0.0,0.0,2.86,1.43,0.00,1.43,0.0,0,0,"0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
3,James Abankwah,ie IRL,"DF,CC",Udinese,it Serie A,2004,21-118,1.0,65.0,8.00,37.0,22.0,7.00,2.00,65.0,0.00,0.00,0.0,0.00,0.0,29.0,219.0,165.0,3.00,1.00,1.00,1.00,3.00,34.0,1.00,0.0,1.0,0.0,0.0,1.02,0.00,0.0,0.0,15.0,0.0,0.0,0.0,0.1,0.1,0.1,0.1,0.06,-0.1,-0.1,4.00,2.00,4.00,0.00,0.0,2.00,3.00,66.7,1.00,2.00,1.00,1.00,1.00,5.00,3.00,0.00,45.0,1.00,1.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,36.0,46.0,10.0,78.3,614.0,206.0,13.0,15.0,2.0,86.7,18.00,21.0,3.00,85.7,3.00,8.00,5.00,37.5,0.0,0.00,0.00,0.00,0.00,2.00,0.0,0.0,4.00,1.00,0.0,0.0,4.00,3.00,0.00,0.0,0.0,0.0,7.00,4.00,2.00,2.00,50.0,1,"1,02","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
5,Yunis Abdelhamid,ma MAR,DF,Saint-Étienne,fr Ligue 1,1987,37-228,11.0,58.3,11.50,37.6,19.5,1.27,0.64,58.3,0.64,0.27,42.9,0.36,57.1,29.3,157.5,76.1,0.36,0.09,0.00,0.73,0.27,35.7,0.27,0.0,2.0,1.0,50.0,0.18,0.09,0.0,0.0,10.8,0.0,0.0,0.0,0.2,0.018182,0.2,0.018182,0.12,-0.2,-0.2,1.55,1.00,1.36,0.18,0.0,0.91,1.45,62.5,0.55,2.36,1.64,0.73,1.18,2.73,5.18,0.09,42.0,3.85,1.83,0.0,0.0,0.00,0.28,0.0,0.0,0.0,0.0,0.18,0.09,39.8,45.9,6.1,86.7,722.9,218.5,13.4,14.5,1.1,91.9,23.90,26.1,2.20,91.6,2.09,4.36,2.27,47.9,0.0,0.01,0.03,-0.01,0.18,2.55,0.0,0.0,2.00,0.17,0.0,0.0,1.39,0.52,0.00,0.0,0.0,0.0,3.65,2.52,1.65,0.87,65.5,"0,55","0,55","0,09","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"

In [ ]:
 df[df['Jugador'] == 'Lamine Yamal']

,Jugador,País,Posc,Equipo,Comp,Nacimiento,Edad,90 s,Toques,TDef. pen.,T3.º def.,T3.º cent.,T3.º ataq.,TAtaq. pen.,TBalón vivo,RegAtt,RegSucc,RegSucc%,Tkld,Tkld%,Participaciones con balón,Dist. tot. Conducc,Dist. prg. conducc,PrgConducc,Conducc1/3,ConducArea,Errores de control,Tackle exit. recibidos,PasesRec,PasesPrgRec,Gls,Tiros,TirosAP,% de TirosAP,T/90,TirosaAP/90,G/T,G/TirosAP,DistTiros,TirosFK,Gol Penalti,Penaltis lanzados,xG,xG/90,npxG,npxG/90,npxG/Sh,G-xG,np:G-xG,Tkl,TklG,tkl3.º def.,tkl3.º cent.,tkl3.º ataq.,RegTkl,AttRegTkl,Tkl%,DesafPerd,Bloqueos,DisBloq,PasesBloq,Intercepciones,Tkl+Int,Despejes,Errores def tiro,Pases balón vivo,Pases balón muerto,Pases de TL,Pases largos,Cambios,Centros,Lanzamientos,Corners,Corners Dentro,Corneres Fuera,Corners recto,Pases FDJ,Pases bloqueados,PasesCompletados,PasesInt.,PasesFallados,% Pases,Dist. Pase. tot.,Dist. pase prg.,PaseCortCmp,PaseCortInt.,PaseCortFallados,% PaseCortCmp,PaseMedCmp,PMedInt.,PaseMedFallados,% PaseMedCmp,PaseLarCmp,PaseLarInt.,PaseLargFallados,%PaseLarCmp,Asist,xAG,xA,A-xAG,PClave,Pas3ºAtaq,PasAreaPen,CentrosArea,PasesPrg,TA,TR,2a amarilla,Faltas,FaltasRec,FDJ,Penal ejecutado,Penal concedido,GolesPP,Recuperaciones,Aéreos Totales,AéreeosGanados,AéreosPerdidos,% de aéreos ganados,Acciones creación tiros,Pases que acaban en tiro,Pases balón muerto llevan a tiro,Regates llevan a tiro,TirosReboteTiro,Faltas rec. llevan a tiro,Acc. def. llevan a tiro,Acciones creación Goles,Pases llevan a gol,Pases balón vivo gol,Pases balón muerto gol,Regates llevan a gol,TirosReboteGol,Faltas rec. llevan a gol,Acc. def llevan a gol
2766,Lamine Yamal,es ESP,DL,Barcelona,es La Liga,2007,17-305,28.7,63.9,0.28,3.21,20.2,41.8,7.35,63.9,9.83,4.95,50.4,3.97,40.4,45.2,314.2,165.2,5.64,2.96,3.1,3.31,1.5,52.3,14.0,7.0,126.0,39.0,31.0,4.39,1.36,0.06,0.18,19.1,0.0,0.0,0.0,9.1,0.317073,9.1,0.317073,0.07,-2.1,-2.1,1.36,0.91,0.17,0.59,0.59,0.52,1.18,44.1,0.66,0.42,0.0,0.42,0.49,1.85,0.1,0.0,45.4,1.41,0.14,1.01,0.11,3.25,0.61,0.65,0.18,0.0,0.0,0.29,1.81,35.0,46.9,11.9,74.7,491.3,141.8,21.8,25.4,3.6,86.0,9.97,13.7,3.73,72.8,1.71,3.69,1.98,46.2,0.42,0.48,0.39,-0.06,2.09,2.44,3.1,0.52,5.02,0.09,0.0,0.0,0.95,1.89,0.41,0.06,0.0,0.0,3.88,0.12,0.03,0.09,25.0,"5,96","5,95","0,1","1,22","0,59","0,35","0,07","0,91","0,9","0,63","0,0","0,14","0,07","0,07","0,0"

In [ ]:
#Función para limpiar errores típicos de FBREF

def Limpiar_errores_fbref(df):
    df = df.copy()

    import pandas as pd
    import numpy as np

    df = df.copy()

    # Eliminar columna 'Rk' si existe
    if 'Rk' in df.columns:
        df = df.drop(columns=['Rk'])

    # Eliminar filas completamente vacías
    df = df.dropna(how='all')

    # Quitar espacios en los nombres de columnas
    df.columns = df.columns.str.strip()

    # Limpiar 'Edad': dejar solo el número de años
    if 'Edad' in df.columns:
        df['Edad'] = df['Edad'].astype(str).str.extract(r'(\d+)').astype(int)

    # Solucionar el problema del país
    df['País'] = df['País'].str.split(' ').str[1]

    #Solucionar el problema de la doble posición
    df['Posc'] = df['Posc'].str.split(',').str[0]

    # Eliminar la primera parte de la columna Comp (liga), y quedarse con la segunda parte
    df['Comp'] = df['Comp'].str.split(' ', n=1).str[1].fillna(df['Comp'])

    # Eliminar filas sin nombre de jugador
    if 'Jugador' in df.columns:
        df = df[df['Jugador'].notna()]

    # Convertir a float las columnas numéricas mal tipadas (si alguna es string)
    for col in df.columns:
        if df[col].dtype == object:
            try:
                df[col] = df[col].str.replace('%', '')  # quitar % si hay
                df[col] = df[col].str.replace(',', '')  # quitar separador de miles
                df[col] = df[col].astype(float)
            except:
                pass  # si no se puede convertir, se deja como está

    #Rellenar los posibles Nan que aparezcan
    df.fillna(0.0, inplace=True)

    return df

In [ ]:
Limpiar_errores_fbref(df)

,Jugador,País,Posc,Equipo,Comp,Nacimiento,Edad,90 s,Toques,TDef. pen.,T3.º def.,T3.º cent.,T3.º ataq.,TAtaq. pen.,TBalón vivo,RegAtt,RegSucc,RegSucc%,Tkld,Tkld%,Participaciones con balón,Dist. tot. Conducc,Dist. prg. conducc,PrgConducc,Conducc1/3,ConducArea,Errores de control,Tackle exit. recibidos,PasesRec,PasesPrgRec,Gls,Tiros,TirosAP,% de TirosAP,T/90,TirosaAP/90,G/T,G/TirosAP,DistTiros,TirosFK,Gol Penalti,Penaltis lanzados,xG,xG/90,npxG,npxG/90,npxG/Sh,G-xG,np:G-xG,Tkl,TklG,tkl3.º def.,tkl3.º cent.,tkl3.º ataq.,RegTkl,AttRegTkl,Tkl%,DesafPerd,Bloqueos,DisBloq,PasesBloq,Intercepciones,Tkl+Int,Despejes,Errores def tiro,Pases balón vivo,Pases balón muerto,Pases de TL,Pases largos,Cambios,Centros,Lanzamientos,Corners,Corners Dentro,Corneres Fuera,Corners recto,Pases FDJ,Pases bloqueados,PasesCompletados,PasesInt.,PasesFallados,% Pases,Dist. Pase. tot.,Dist. pase prg.,PaseCortCmp,PaseCortInt.,PaseCortFallados,% PaseCortCmp,PaseMedCmp,PMedInt.,PaseMedFallados,% PaseMedCmp,PaseLarCmp,PaseLarInt.,PaseLargFallados,%PaseLarCmp,Asist,xAG,xA,A-xAG,PClave,Pas3ºAtaq,PasAreaPen,CentrosArea,PasesPrg,TA,TR,2a amarilla,Faltas,FaltasRec,FDJ,Penal ejecutado,Penal concedido,GolesPP,Recuperaciones,Aéreos Totales,AéreeosGanados,AéreosPerdidos,% de aéreos ganados,Acciones creación tiros,Pases que acaban en tiro,Pases balón muerto llevan a tiro,Regates llevan a tiro,TirosReboteTiro,Faltas rec. llevan a tiro,Acc. def. llevan a tiro,Acciones creación Goles,Pases llevan a gol,Pases balón vivo gol,Pases balón muerto gol,Regates llevan a gol,TirosReboteGol,Faltas rec. llevan a gol,Acc. def llevan a gol
0,Max Aarons_2,ENG,DF,Bournemouth,Premier League,2000,25,1.0,73.0,2.00,19.00,40.00,15.00,0.00,73.0,2.00,0.00,0.0,1.00,50.0,41.00,152.0,68.0,1.00,0.00,0.00,1.00,0.00,40.0,3.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.00,0.0,0.0,2.00,2.00,1.00,1.00,0.00,1.00,1.00,100.0,0.00,3.00,1.00,2.00,1.00,3.00,0.00,0.00,51.0,12.00,2.00,0.00,0.00,2.00,10.00,0.00,0.00,0.00,0.0,0.00,1.00,50.00,63.0,13.00,79.4,887.0,361.0,21.00,25.00,4.00,84.0,24.00,29.00,5.00,82.8,4.00,7.00,3.00,57.1,0.00,0.00,0.00,0.00,0.00,8.00,0.00,0.00,8.00,0.00,0.00,0.00,0.00,2.00,0.00,0.00,0.00,0.0,7.00,0.00,0.00,0.00,0.0,2.0,209.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Max Aarons,ENG,DF,Valencia,La Liga,2000,25,1.2,49.2,0.83,14.20,10.00,25.00,0.00,49.2,3.33,0.83,25.0,1.67,50.0,25.00,79.2,34.2,0.00,2.50,0.00,1.67,0.83,27.5,6.67,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.00,0.0,0.0,2.50,2.50,1.67,0.83,0.00,2.50,2.50,100.0,0.00,0.83,0.00,0.83,0.00,2.50,2.50,0.00,29.2,5.83,0.00,0.00,0.00,1.67,5.83,0.00,0.00,0.00,0.0,0.00,0.83,24.20,35.0,10.80,69.0,345.0,108.3,13.30,18.30,5.00,72.7,9.17,13.30,4.13,68.8,0.83,1.67,0.84,50.0,0.00,0.00,0.00,0.00,0.83,0.83,0.00,0.00,3.33,1.54,0.00,0.00,0.00,1.54,0.00,0.00,0.00,0.0,5.38,2.31,1.54,0.77,66.7,83.0,87.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Rodrigo Abajas,ESP,DF,Valencia,La Liga,2003,22,0.7,51.4,1.43,11.40,27.10,12.90,1.43,51.4,1.43,1.43,100.0,0.00,0.0,18.60,144.3,95.7,4.29,2.86,1.43,0.00,2.86,22.9,4.29,0.0,1.0,0.0,0.0,1.38,0.00,0.00,0.00,24.5,0.0,0.0,0.0,0.1,0.142857,0.1,0.142857,0.07,-0.1,-0.1,4.29,2.86,2.86,1.43,0.00,4.29,4.29,100.0,0.00,1.43,0.00,1.43,1.43,5.71,0.00,0.00,30.0,11.40,0.00,0.00,0.00,1.43,11.40,0.00,0.00,0.00,0.0,0.00,2.86,24.30,41.4,17.10,58.6,382.9,157.1,15.70,20.00,4.30,78.6,5.71,10.00,4.29,57.1,2.86,10.00,7.14,28.6,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.86,1.43,0.00,0.00,2.86,0.00,1.43,0.00,0.00,0.0,2.86,1.43,0.00,1.43,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,James Abankwah,IRL,DF,Udinese,Serie A,2004,21,1.0,65.0,8.00,37.00,22.00,7.00,2.00,65.0,0.00,0.00,0.0,0.00,0.0,29.00,219.0,165.0,3.00,1.00,1.00,1.00,3.00,34.0,1.00,0.0,1.0,0.0,0.0,1.02,0.00,0.00,0.00,15.0,0.0,0.0,0.0,0.1,0.1,0.1,0.1,0.06,-0.1,-0.1,4.00,2.00,4.00,0.00,0.00,2.00,3.00,66.7,1.00,2.00,1.00,1.00,1.00,5.00,3.00,0.00,45.0,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,36.00,46.0,10.00,78.3,614.0,206.0,13.00,15.00,2.00,86.7,18.00,21.00,3.00,85.7,3.00,8.00,5.00,37.5,0.00,0.00,0.00,0.00,0.00,2.00,0.00,0.00,4.00,1.00,0.00,0.00,4.00,3.00,0.00,0.00,0.00,0.0,7.00,4.00,2.00,2.00,50.0,1.0,102.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Yunis Abdelhamid,MAR,DF,Saint-Étienne,Ligue 1,1987,37,11.0,58.3,11.50,37.60,19.50,1.27,0.64,58.3,0.64,0.27,42.9,0.36,57.1,29.30,157.5,76.1,0.36,0.09,0.00,0.73,0.27,35.7,0.27,0.0,2.0,1.0,50.0,0.18,0.09,0.00,0.00,10.8,0.0,0.0,0.0,0.2,0.018182,0.2,0.018182,0.12,-0.2,-0.2,1.55,1.00,1.36,0.18,0.00,0.91,1.45,62.5,0.55,2.36,1.64,0.73,1.18,2.73,5.18,0.09,42.0,3.85,1.83,0.00,0.00,0.00,0.28,0.00,0.00,0.00,0.0,0.18,0.09,39.80,45.9,6.10,86.7,722.9,218.5,13.40,14.50,1.10,91.9,23.90,26.10,2.20,91.6,2.09,4.36,2.27,47.9,0.00,0.01,0.03,-0.01,0.18,2.55,0.00,0.00,2.00,0.17,0.00,0.00,1.39,0.52,0.00,0.00,0.00,0.0,3.65,2.52,1.65,0.87,65.5,55.0,55.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Himad Abdelli,ALG,CC,Angers,Ligue 1,1999,25,30.6,62.7,1.14,9.22,36.50,18.50,1.54,62.6,3.89,1.83,47.1,1.99,51.3,36.90,236.7,134.6,3.33,2.71,0.56,1.73,1.67,45.5,3.56,6.0,32.0,7.0,21.9,1.05,0.23,0.09,0.43,22.3,0.0,3.0,4.0,6.3,0.205882,3.1,0.101307,0.10,-0.3,-0.1,1.54,1.01,0.39,0.65,0.49,0.46,1.54,29.8,1.08,0.72,0.03,0.69,0.82,2.35,0.88,0.07,49.7,3.34,1.28,0.78,0.41,1.35,0.47,0.27,0.14,0.07,0.0,0.34,1.05,43.20,52.6,9.40,82.2,675.6,187.3,22.50,25.50,3.00,88.1,16.60,19.10,2.50,86.8,2.52,4.64,2.12,54.2,0.03,0.10,0.11,-0.07,1.14,5.20,1.18,0.07,6.50,0.13,0.00,0.00,1.52,1.01,0.09,0.00,0.00,0.0,6.11,1.04,0.41,0.63,39.4,288.0,288.0,7.0,16.0,3.0,1.0,1.0,16.0,16.0,1.0,0.0,7.0,0.0,0.0,0.0
7,Mohamed Abdelmoneim,EGY,DF,Nice,Ligue 1,1999,26,9.5,66.8,7.37,27.40,34.80,4.84,0.32,66.8,0.42,0.11,25.0,0.21,50.0,36.00,150.2,86.5,0.63,0.42,0.00,0.42,0.32,40.6,0.53,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.00,0.0,0.0,2.21,1.47,1.26,0.63,0.32,1.37,2.32,59.1,0.95,1.16,0.53,0.63,1.58,3.79,5.89,0.11,51.9,2.95,2.21,0.00,0.74,0.21,0.53,0.00,0.00,0.00,0.0,0.00,0.21,49.60,54.8,5.20,90.4,873.6,275.8,20.50,21.80,1.30,94.2,25.40,27.30,1.90,93.1,2.84,4.63,1.79,61.4,0.00,0.00,0.02,0.00,0.00,4.32,0.11,0.00,5.47,0.21,0.00,0.00,0.95,1.05,0.00,0.00,0.00,0.0,5.26,5.26,3.26,2.00,62.0,84.0,84.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Ali Abdi,TUN,DF,Nice,Ligue 1,1993,31,15.4,56.8,3.31,14.70,22.30,20.30,3.12,56.8,1.82,0.78,42.9,0.97,53.6,25.10,119.4,63.1,2.21,0.97,0.52,2.08,0.91,30.8,6.43,4.0,28.0,10.0,35.7,1.82,0.65,0.14,0.40,17.4,1.0,0.0,0.0,3.4,0.220779,3.4,0.220779,0.14,0.6,0.6,2.79,1.62,1.17,0.91,0.71,1.82,2.79,65.1,0.97,1.30,0.39,0.91,1.30,4.09,2.40,0.00,35.6,7.38,0.81,0.00,0.13,3.29,6.58,0.00,0.00,0.00,0.0,0.27,1.34,32.10,43.4,11.30,73.8,504.3,174.5,17.30,20.20,2.90,85.5,11.90,15.60,3.70,76.7,2.08,4.61,2.53,45.1,0.13,0.12,0.11,0.01,1.23,1.23,1.36,0.45,2.73,0.13,0.00,0.00,1.74,0.90,0.32,0.00,0.00,0.0,4.65,2.32,1.42,0.90,61.1,286.0,286.0,19.0,26.0,26.0,0.0,6.0,19.0,19.0,6.0,6.0,0.0,6.0,0.0,0.0
9,Saud Abdulhamid,KSA,DF,Roma,Serie A,1999,25,2.3,68.3,0.00,11.70,32.60,24.30,3.04,68.3,3.48,1.30,37.5,0.87,25.0,39.10,173.5,76.1,2.61,0.87,0.87,2.17,0.43,47.0,11.30,0.0,1.0,0.0,0.0,0.44,0.00,0.00,0.00,24.7,0.0,0.0,0.0,0.0,0,0.0,0,0.03,0.0,0.0,1.30,0.87,0.87,0.00,0.43,0.43,0.43,100.0,0.00,0.87,0.00,0.87,0.87,2.17,0.00,0.00,44.8,14.30,0.43,0.00,0.00,3.04,13.90,0.00,0.00,0.00,0.0,0.00,1.30,51.30,59.1,7.80,86.8,767.8,160.0,28.30,30.00,1.70,94.2,21.30,23.90,2.60,89.1,0.87,2.61,1.74,33.3,0.43,0.09,0.09,0.35,0.87,1.74,1.74,0.87,3.91,0.00,0.00,0.00,0.87,2.17,0.00,0.00,0.43,0.0,1.30,0.43,0.00,0.43,0.0,261.0,265.0,0.0,0.0,0.0,43.0,0.0,43.0,44.0,43.0,0.0,0.0,0.0,0.0,0.0
10,Abel,ESP,DF,Osasuna,La Liga,2000,24,22.4,57.1,2.81,16.30,26.00,15.20,0.80,57.1,1.56,0.80,51.4,0.58,37.1,26.20,141.8,76.8,2.19,1.92,0.31,1.21,0.80,29.2,3.93,2.0,11.0,4.0,36.4,0.49,0.18,0.18,0.50,23.8,0.0,0.0,0.0,0.5,0.022321,0.5,0.022321,0.04,1.5,1.5,2.63,1.56,1.25,1.07,0.31,1.65,2.63,62.7,0.98,1.25,0.18,1.07,0.80,3.44,2.72,0.09,36.5,9.55,0.58,0.13,0.09,3.71,8.97,0.00,0.00,0.00,0.0,0.18,2.05,33.40,46.2,12.80,72.4,557.9,219.6,16.60,18.80,2.20,88.1,13.60,17.20,3.60,78.8,2.54,7.01,4.47,36.3,0.00,0.04,0.06,-0.04,0.67,2.46,0.71,0.54,3.17,0.13,0.00,0.00,1.09,1.39,0.13,0.00,0.04,0.0,4.61,1.61,0.87,0.74,54.1,161.0,161.0,9.0,22.0,0.0,4.0,4.0,18.0,18.0,9.0,0.0,4.0,0.0,0.0,4.0
11,Nabil Aberdin,FRA,CC,Getafe,La Liga,2002,22,2.9,30.0,2.07,7.24,19.30,3.45,0.69,30.0,1.03,0.69,66.7,0.34,33.3,11.70,51.0,25.5,0.69,0.00,0.00,0.34,0.34,12.4,0.69,0.0,2.0,0.0,0.0,0.68,0.00,0.00,0.00,31.2,0.0,0.0,0.0,0.0,0,0.0,0,0.02,0.0,0.0,2.07,1.38,1.03,1.03,0.00,0.34,0.34,100.0,0.00,1.03,0.00,1.03,0.00,2.07,1.72,0.00,20.0,0.69,0.69,0.00,0.34,0.00,0.00,0.00,0.00,0.00,0.0,0.34,1.03,12.40,21.0,8.60,59.0,234.5,92.1,4.14,6.90,2.76,60.0,4.14,6.55,2.41,63.2,2.76,4.48,1.72,61.5,0.00,0.00,0.03,0.00,0.34,2.41,0.69,0.00,2.07,0.34,0.00,0.00,2.41,2.07,0.00,0.00,0.00,0.0,2.76,4.48,3.45,1.03,76.9,103.0,103.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,Oliver Abildgaard,DEN,CC,Como,Serie A,1996,28,0.1,20.0,0.00,10.00,10.00,0.00,0.00,20.0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,10.00,0.00,10.00,0.00,0.00,0.00,0.00,10.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,10.00,10.0,0.00,100.0,210.0,70.0,0.00,0.00,0.00,0.0,10.00,10.00,0.00,100.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,Matthis Abline,FRA,DL,Nantes,Ligue 1,2003,22,29.8,28.4,1.07,2.45,12.30,14.20,4.56,28.4,2.79,1.11,39.8,1.58,56.6,19.00,118.0,56.3,2.35,1.34,1.31,3.02,2.05,22.2,5.40,8.0,71.0,25.0,35.2,2.39,0.84,0.10,0.28,15.1,0.0,1.0,1.0,7.9,0.265101,7.1,0.238255,0.10,0.1,-0.1,0.37,0.17,0.07,0.13,0.17,0.10,0.30,33.3,0.20,0.50,0.03,0.47,0.10,0.47,1.14,0.03,16.3,0.87,0.03,0.10,0.14,1.04,0.03,0.00,0.00,0.00,0.0,0.03,0.87,11.20,17.3,6.10,64.7,162.1,30.8,5.94,8.26,2.32,72.0,3.83,5.17,1.34,74.0,0.57,1.17,0.60,48.6,0.07,0.13,0.11,-0.06,0.87,0.70,0.50,0.13,1.48,0.10,0.00,0.00,1.10,1.72,0.16,0.00,0.00,0.0,2.69,4.55,2.08,2.47,45.7,198.0,198.0,0.0,27.0,17.0,1.0,3.0,27.0,27.0,2.0,0.0,7.0,0.0,0.0,0.0
14,Abner,BRA,DF,Lyon,Ligue 1,2000,24,12.1,65.3,3.31,17.00,29.80,18.60,1.82,65.3,0.99,0.50,50.0,0.50,50.0,35.20,159.2,102.4,2.56,1.32,0.41,1.16,0.66,42.4,4.55,1.0,7.0,3.0,42.9,0.58,0.25,0.14,0.33,17.7,0.0,0.0,0.0,0.6,0.049587,0.6,0.049587,0.08,0.4,0.4,2.40,1.65,0.99,0.83,0.58,1.74,2.64,65.6,0.91,1.24,0.17,1.07,0.41,2.81,3.39,0.00,47.5,8.02,0.74,0.08,0.41,2.56,6.78,0.50,0.50,0.00,0.0,0.17,1.49,46.90,55.7,8.80,84.3,690.5,288.8,27.70,30.20,2.50,91.5,15.00,17.40,2.40,86.2,2.73,4.55,1.82,60.0,0.08,0.09,0.19,-0.01,0.91,3.72,0.91,0.17,5.45,0.08,0.00,0.00,1.32,0.33,0.00,0.00,0.00,0.0,3.72,1.32,0.58,0.74,43.8,207.0,207.0,25.0,0.0,8.0,0.0,0.0,8.0,8.0,8.0,0.0,0.0,0.0,0.0,0.0
15,Zakaria Aboukhlal,MAR,CC,Toulouse,Ligue 1,2000,25,20.8,28.8,0.24,2.69,9.33,17.00,5.34,28.7,2.36,0.72,30.6,1.54,65.3,17.60,89.7,41.2,1.59,1.11,0.91,3.03,1.20,21.3,7.69,7.0,60.0,25.0,41.7,2.89,1.20,0.10,0.24,14.5,0.0,1.0,2.0,10.1,0.485577,8.5,0.408654,0.14,-3.1,-2.5,1.01,0.58,0.29,0.38,0.34,0.19,1.01,19.0,0.82,0.77,0.05,0.72,0.29,1.30,0.38,0.00,15.9,0.63,0.05,0.00,0.00,1.61,0.34,0.15,0.10,0.00,0.0,0.15,0.68,10.40,16.5,6.10,63.1,131.2,36.1,6.88,9.18,2.30,74.9,2.60,4.42,1.82,58.7,0.29,0.67,0.38,42.9,0.10,0.08,0.10,0.02,0.58,0.77,0.48,0.19,1.06,0.19,0.00,0.00,1.66,1.18,0.62,0.09,0.00,0.0,2.89,2.84,1.04,1.80,36.7,163.0,164.0,0.0,19.0,29.0,19.0,5.0,34.0,34.0,14.0,0.0,5.0,0.0,14.0,0.0
16,Abdel Abqar,MAR,DF,Alavés,La Liga,1999,26,27.4,45.7,5.84,24.10,19.90,2.12,0.91,45.7,0.15,0.11,75.0,0.04,25.0,23.10,128.9,73.5,0.58,0.26,0.00,0.66,0.11,23.7,0.15,0.0,12.0,1.0,8.3,0.44,0.04,0.00,0.00,8.0,0.0,0.0,0.0,0.9,0.032847,0.9,0.032847,0.08,-0.9,-0.9,1.31,0.84,0.88,0.40,0.04,0.73,1.24,58.8,0.51,1.02,0.66,0.36,1.42,2.74,5.33,0.04,32.4,1.75,1.46,0.04,0.62,0.18,0.26,0.00,0.00,0.00,0.0,0.11,0.22,26.20,34.3,8.10,76.6,585.4,210.6,6.57,7.08,0.51,92.8,15.40,16.80,1.40,91.5,4.16,9.42,5.26,44.2,0.04,0.01,0.01,0.03,0.29,2.45,0.36,0.07,2.88,0.47,0.00,0.00,1.72,1.13,0.07,0.04,0.07,0.0,3.18,2.74,1.46,1.28,53.3,91.0,91.0,0.0,0.0,7.0,4.0,7.0,11.0,11.0,7.0,0.0,0.0,0.0,4.0,0.0
18,Tammy Abraham,ENG,DL,Milan,Serie A,1997,27,13.1,28.0,1.53,3.51,13.10,11.40,4.35,27.9,1.07,0.31,28.6,0.76,71.4,12.10,43.7,15.6,0.61,0.46,0.31,1.68,0.99,18.4,5.27,3.0,26.0,11.0,42.3,1.98,0.84,0.08,0.18,13.4,0.0,1.0,2.0,7.1,0.541985,5.4,0.412214,0.21,-4.1,-3.4,1.30,0.84,0.15,0.76,0.38,0.46,0.61,75.0,0.15,0.99,0.00,0.99,0.15,1.45,1.22,0.00,15.5,1.30,0.00,0.38,0.00,0.23,0.00,0.00,0.00,0.00,0.0,0.08,0.46,11.60,16.9,5.30,68.8,149.3,40.8,7.18,9.47,2.29,75.8,3.51,5.65,2.14,62.2,0.23,0.46,0.23,50.0,0.31,0.17,0.10,0.14,1.07,0.99,0.76,0.00,1.98,0.08,0.00,0.00,1.76,0.92,0.53,0.08,0.00,0.0,0.92,5.27,2.75,2.52,52.2,252.0,251.0,0.0,0.0,31.0,8.0,0.0,69.0,68.0,53.0,0.0,0.0,8.0,8.0,0.0
19,Federico Accornero,ITA,CC,Genoa,Serie A,2004,21,0.1,80.0,10.00,20.00,30.00,30.00,0.00,80.0,0.00,0.00,0.0,0.00,0.0,50.00,250.0,180.0,0.00,10.00,0.00,20.00,0.00,50.0,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,60.0,0.00,0.00,0.00,0.00,10.00,0.00,0.00,0.00,0.00,0.0,0.00,10.00,40.00,60.0,20.00,66.7,550.0,190.0,20.00,30.00,10.00,66.7,20.00,20.00,0.00,100.0,0.00,10.00,10.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,10.00,10.00,0.00,10.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,Francesco Acerbi,ITA,DF,Inter,Serie A,1988,37,17.7,77.9,7.29,34.10,38.50,5.48,0.96,77.9,0.17,0.17,100.0,0.00,0.0,48.20,215.9,106.4,0.96,0.85,0.06,0.40,0.11,57.3,1.13,0.0,4.0,1.0,25.0,0.23,0.06,0.00,0.00,11.2,0.0,0.0,0.0,0.3,0.016949,0.3,0.016949,0.08,-0.3,-0.3,1.30,1.07,0.90,0.40,0.00,0.62,0.96,64.7,0.34,1.19,0.85,0.34,1.47,2.77,4.35,0.00,65.8,2.11,1.37,0.00,0.06,0.57,0.46,0.00,0.00,0.00,0.0,0.11,0.29,62.70,67.7,5.00,92.6,1173.0,325.6,20.80,22.40,1.60,92.9,36.70,38.20,1.50,96.2,4.52,5.65,1.13,80.0,0.06,0.03,0.06,0.02,0.51,2.88,0.40,0.28,3.16,0.00,0.00,0.00,0.58,0.95,0.11,0.00,0.00,0.0,3.26,4.79,3.21,1.58,67.0,107.0,108.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0
21,Joshua Acheampong,ENG,DF,Chelsea,Premier League,2006,19,1.9,72.1,3.68,25.30,42.60,4.21,1.58,72.1,1.05,0.53,50.0,0.00,0.0,55.80,373.2,215.3,0.00,1.05,0.00,1.05,0.00,58.4,0.00,0.0,2.0,0.0,0.0,1.06,0.00,0.00,0.00,8.9,0.0,0.0,0.0,0.2,0.105263,0.2,0.105263,0.11,-0.2,-0.2,1.05,0.53,1.05,0.00,0.00,1.05,1.05,100.0,0.00,0.53,0.00,0.53,0.53,1.58,1.05,0.00,63.7,1.58,1.05,0.00,0.00,0.00,0.53,0.00,0.00,0.00,0.0,0.00,1.05,54.70,65.3,10.60,83.9,1065.8,371.1,15.30,16.80,1.50,90.6,33.20,35.80,2.60,92.6,5.79,10.50,4.71,55.0,0.00,0.00,0.00,0.00,0.00,3.16,0.00,0.00,4.21,0.53,0.00,0.00,0.00,0.53,0.00,0.00,0.00,0.0,3.68,3.69,0.53,3.16,14.3,105.0,106.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,Akor Adams_2,NGA,DL,Sevilla,La Liga,2000,25,1.5,22.7,0.67,2.67,12.00,8.00,0.67,22.7,0.67,0.67,100.0,0.00,0.0,3.33,12.0,0.0,0.00,0.00,0.00,1.33,0.00,13.3,3.33,0.0,2.0,1.0,50.0,1.34,0.67,0.00,0.00,22.2,0.0,0.0,0.0,0.4,0.266667,0.4,0.266667,0.22,-0.4,-0.4,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.67,0.00,0.67,0.00,0.00,0.67,0.00,16.0,2.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,13.30,18.0,4.70,74.1,222.7,32.0,6.00,8.00,2.00,75.0,4.67,6.00,1.33,77.8,2.00,3.33,1.33,60.0,0.00,0.00,0.00,0.00,0.00,2.00,0.67,0.00,3.33,0.00,0.00,0.00,0.67,0.00,0.67,0.00,0.00,0.0,2.67,10.67,4.00,6.67,37.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,Akor Adams,NGA,DL,Montpellier,Ligue 1,2000,25,11.9,21.1,0.42,1.60,9.92,9.83,4.12,21.1,1.18,0.59,50.0,0.50,42.9,10.60,55.5,23.4,0.92,0.42,0.59,1.34,1.18,14.6,3.78,3.0,26.0,12.0,46.2,2.18,1.00,0.12,0.25,13.3,0.0,0.0,0.0,4.3,0.361345,4.3,0.361345,0.16,-1.3,-1.3,0.34,0.25,0.08,0.17,0.08,0.25,0.34,75.0,0.08,0.17,0.08,0.08,0.08,0.42,0.42,0.08,13.4,1.43,0.00,0.08,0.17,0.42,0.00,0.00,0.00,0.00,0.0,0.17,0.59,9.41,15.0,5.59,62.6,129.4,16.6,6.05,8.49,2.44,71.3,2.69,4.12,1.43,65.3,0.25,0.84,0.59,30.0,0.08,0.08,0.01,0.00,1.01,0.67,0.00,0.00,0.50,0.17,0.00,0.00,1.43,0.67,1.34,0.17,0.00,0.0,2.02,4.62,2.35,2.27,50.9,21.0,209.0,0.0,34.0,8.0,17.0,0.0,42.0,42.0,17.0,0.0,8.0,0.0,17.0,0.0
24,Che Adams,SCO,DL,Torino,Serie A,1996,28,27.5,27.3,0.62,1.85,13.30,12.50,3.49,27.3,1.35,0.40,29.7,0.80,59.5,17.50,72.3,25.3,0.80,0.65,0.29,2.15,1.20,21.4,5.24,9.0,60.0,23.0,38.3,2.18,0.84,0.15,0.39,15.8,0.0,0.0,1.0,8.9,0.323636,8.1,0.294545,0.13,0.1,0.9,0.36,0.18,0.04,0.15,0.18,0.00,0.15,0.0,0.15,0.40,0.18,0.22,0.07,0.44,0.65,0.00,17.2,1.47,0.11,0.15,0.19,0.38,0.04,0.00,0.00,0.00,0.0,0.04,0.64,14.00,18.9,4.90,74.1,221.6,40.0,7.42,9.53,2.11,77.9,4.55,5.71,1.16,79.6,1.27,1.82,0.55,70.0,0.11,0.07,0.10,0.04,0.91,1.13,0.22,0.00,1.31,0.07,0.00,0.00,0.98,1.36,0.78,0.00,0.00,0.0,1.69,3.32,1.22,2.10,36.7,225.0,226.0,4.0,0.0,29.0,18.0,0.0,18.0,18.0,15.0,0.0,0.0,4.0,0.0,0.0
25,Tyler Adams,USA,CC,Bournemouth,Premier League,1999,26,19.8,62.0,2.93,16.40,36.00,10.20,0.86,62.0,0.81,0.15,18.8,0.45,56.3,29.80,147.5,65.7,0.66,0.91,0.05,1.41,0.61,34.5,0.45,0.0,8.0,2.0,25.0,0.40,0.10,0.00,0.00,16.1,0.0,0.0,0.0,1.6,0.080808,1.6,0.080808,0.19,-1.6,-1.6,3.94,2.42,1.21,2.37,0.35,1.82,3.43,52.9,1.62,1.67,0.51,1.16,1.62,5.56,2.02,0.00,45.5,1.84,1.63,0.11,0.00,0.16,0.21,0.00,0.00,0.00,0.0,0.26,0.58,41.30,49.1,7.80,84.0,652.3,163.7,20.10,22.50,2.40,89.0,18.00,20.40,2.40,88.6,1.62,2.93,1.31,55.2,0.15,0.05,0.03,0.10,0.86,3.18,0.10,0.05,3.48,0.32,0.00,0.00,2.06,0.96,0.00,0.00,0.05,0.0,5.23,2.25,1.42,0.83,63.3,192.0,192.0,0.0,0.0,5.0,0.0,2.0,2.0,2.0,15.0,0.0,0.0,0.0,0.0,5.0
26,Junior Adamu,AUT,DL,Freiburg,Bundesliga,2001,23,16.4,31.3,1.16,3.11,14.50,14.10,4.70,31.3,1.77,0.61,34.5,1.10,62.1,16.30,61.6,20.9,0.49,0.30,0.24,3.48,1.28,20.6,4.94,2.0,34.0,11.0,32.4,2.08,0.67,0.06,0.18,12.4,0.0,0.0,0.0,5.2,0.317073,5.2,0.317073,0.15,-3.2,-3.2,0.55,0.18,0.18,0.18,0.18,0.18,0.61,30.0,0.43,0.85,0.00,0.85,0.73,1.28,1.16,0.00,17.6,0.91,0.00,0.13,0.00,0.32,0.13,0.00,0.00,0.00,0.0,0.13,0.78,11.60,18.5,6.90,62.7,135.8,17.3,7.32,10.70,3.38,68.6,2.74,4.09,1.35,67.2,0.06,0.30,0.24,20.0,0.12,0.15,0.12,-0.02,1.04,0.30,0.49,0.00,0.85,0.29,0.06,0.00,2.21,1.28,0.99,0.00,0.00,0.0,3.02,9.36,3.08,6.28,32.9,177.0,177.0,0.0,6.0,18.0,18.0,0.0,18.0,18.0,12.0,0.0,0.0,6.0,0.0,0.0
27,Tosin Adarabioyo,ENG,DF,Chelsea,Premier League,1997,27,13.7,87.4,11.70,41.60,44.00,1.90,0.95,87.4,0.36,0.29,80.0,0.00,0.0,52.00,215.3,123.4,0.36,0.15,0.00,0.22,0.00,66.9,0.07,1.0,12.0,2.0,16.7,0.88,0.15,0.08,0.50,12.5,0.0,0.0,0.0,0.9,0.065693,0.9,0.065693,0.08,0.1,0.1,1.02,0.73,0.73,0.29,0.00,0.58,0.88,66.7,0.29,0.66,0.51,0.15,0.73,1.75,4.53,0.00,76.2,2.55,1.39,0.15,0.22,0.00,0.29,0.00,0.00,0.00,0.0,0.15,0.22,72.10,78.9,6.80,91.4,1321.5,472.9,27.30,28.50,1.20,95.7,40.40,42.60,2.20,94.9,4.23,6.93,2.70,61.1,0.07,0.01,0.01,0.06,0.07,3.87,0.07,0.00,2.70,0.25,0.00,0.00,0.51,0.57,0.06,0.00,0.00,0.0,2.61,4.46,2.68,1.78,60.0,88.0,88.0,0.0,0.0,36.0,0.0,0.0,7.0,7.0,0.0,0.0,0.0,7.0,0.0,0.0
28,Martin Adeline,FRA,CC,Reims,Ligue 1,2003,21,0.3,46.7,6.67,26.70,13.30,6.67,3.33,46.7,0.00,0.00,0.0,0.00,0.0,20.00,116.7,30.0,3.33,0.00,3.33,0.00,0.00,30.0,3.33,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.00,0.0,0.0,3.33,3.33,0.00,3.33,0.00,3.33,6.67,50.0,3.33,0.00,0.00,0.00,0.00,3.33,6.67,0.00,33.3,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,26.70,33.3,6.60,80.0,460.0,36.7,10.00,10.00,0.00,100.0,10.00,13.30,3.30,75.0,3.33,6.67,3.34,50.0,0.00,0.00,0.00,0.00,0.00,3.33,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.33,0.00,0.00,0.00,0.0,0.00,3.33,0.00,3.33,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
dftop = Limpiar_errores_fbref(df)

In [ ]:
dftop.head()

,Jugador,País,Posc,Equipo,Comp,Nacimiento,Edad,90 s,Toques,TDef. pen.,T3.º def.,T3.º cent.,T3.º ataq.,TAtaq. pen.,TBalón vivo,RegAtt,RegSucc,RegSucc%,Tkld,Tkld%,Participaciones con balón,Dist. tot. Conducc,Dist. prg. conducc,PrgConducc,Conducc1/3,ConducArea,Errores de control,Tackle exit. recibidos,PasesRec,PasesPrgRec,Gls,Tiros,TirosAP,% de TirosAP,T/90,TirosaAP/90,G/T,G/TirosAP,DistTiros,TirosFK,Gol Penalti,Penaltis lanzados,xG,xG/90,npxG,npxG/90,npxG/Sh,G-xG,np:G-xG,Tkl,TklG,tkl3.º def.,tkl3.º cent.,tkl3.º ataq.,RegTkl,AttRegTkl,Tkl%,DesafPerd,Bloqueos,DisBloq,PasesBloq,Intercepciones,Tkl+Int,Despejes,Errores def tiro,Pases balón vivo,Pases balón muerto,Pases de TL,Pases largos,Cambios,Centros,Lanzamientos,Corners,Corners Dentro,Corneres Fuera,Corners recto,Pases FDJ,Pases bloqueados,PasesCompletados,PasesInt.,PasesFallados,% Pases,Dist. Pase. tot.,Dist. pase prg.,PaseCortCmp,PaseCortInt.,PaseCortFallados,% PaseCortCmp,PaseMedCmp,PMedInt.,PaseMedFallados,% PaseMedCmp,PaseLarCmp,PaseLarInt.,PaseLargFallados,%PaseLarCmp,Asist,xAG,xA,A-xAG,PClave,Pas3ºAtaq,PasAreaPen,CentrosArea,PasesPrg,TA,TR,2a amarilla,Faltas,FaltasRec,FDJ,Penal ejecutado,Penal concedido,GolesPP,Recuperaciones,Aéreos Totales,AéreeosGanados,AéreosPerdidos,% de aéreos ganados,Acciones creación tiros,Pases que acaban en tiro,Pases balón muerto llevan a tiro,Regates llevan a tiro,TirosReboteTiro,Faltas rec. llevan a tiro,Acc. def. llevan a tiro,Acciones creación Goles,Pases llevan a gol,Pases balón vivo gol,Pases balón muerto gol,Regates llevan a gol,TirosReboteGol,Faltas rec. llevan a gol,Acc. def llevan a gol
0,Max Aarons_2,ENG,DF,Bournemouth,Premier League,2000,25,1.0,73.0,2.00,19.0,40.0,15.00,0.00,73.0,2.00,0.00,0.0,1.00,50.0,41.0,152.0,68.0,1.00,0.00,0.00,1.00,0.00,40.0,3.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.00,0.0,0.0,2.00,2.00,1.00,1.00,0.0,1.00,1.00,100.0,0.00,3.00,1.00,2.00,1.00,3.00,0.00,0.00,51.0,12.00,2.00,0.0,0.0,2.00,10.00,0.0,0.0,0.0,0.0,0.00,1.00,50.0,63.0,13.0,79.4,887.0,361.0,21.0,25.0,4.0,84.0,24.00,29.0,5.00,82.8,4.00,7.00,3.00,57.1,0.0,0.00,0.00,0.00,0.00,8.00,0.0,0.0,8.00,0.00,0.0,0.0,0.00,2.00,0.00,0.0,0.0,0.0,7.00,0.00,0.00,0.00,0.0,2.0,209.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Max Aarons,ENG,DF,Valencia,La Liga,2000,25,1.2,49.2,0.83,14.2,10.0,25.00,0.00,49.2,3.33,0.83,25.0,1.67,50.0,25.0,79.2,34.2,0.00,2.50,0.00,1.67,0.83,27.5,6.67,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.00,0.0,0.0,2.50,2.50,1.67,0.83,0.0,2.50,2.50,100.0,0.00,0.83,0.00,0.83,0.00,2.50,2.50,0.00,29.2,5.83,0.00,0.0,0.0,1.67,5.83,0.0,0.0,0.0,0.0,0.00,0.83,24.2,35.0,10.8,69.0,345.0,108.3,13.3,18.3,5.0,72.7,9.17,13.3,4.13,68.8,0.83,1.67,0.84,50.0,0.0,0.00,0.00,0.00,0.83,0.83,0.0,0.0,3.33,1.54,0.0,0.0,0.00,1.54,0.00,0.0,0.0,0.0,5.38,2.31,1.54,0.77,66.7,83.0,87.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Rodrigo Abajas,ESP,DF,Valencia,La Liga,2003,22,0.7,51.4,1.43,11.4,27.1,12.90,1.43,51.4,1.43,1.43,100.0,0.00,0.0,18.6,144.3,95.7,4.29,2.86,1.43,0.00,2.86,22.9,4.29,0.0,1.0,0.0,0.0,1.38,0.00,0.0,0.0,24.5,0.0,0.0,0.0,0.1,0.142857,0.1,0.142857,0.07,-0.1,-0.1,4.29,2.86,2.86,1.43,0.0,4.29,4.29,100.0,0.00,1.43,0.00,1.43,1.43,5.71,0.00,0.00,30.0,11.40,0.00,0.0,0.0,1.43,11.40,0.0,0.0,0.0,0.0,0.00,2.86,24.3,41.4,17.1,58.6,382.9,157.1,15.7,20.0,4.3,78.6,5.71,10.0,4.29,57.1,2.86,10.00,7.14,28.6,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0,2.86,1.43,0.0,0.0,2.86,0.00,1.43,0.0,0.0,0.0,2.86,1.43,0.00,1.43,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,James Abankwah,IRL,DF,Udinese,Serie A,2004,21,1.0,65.0,8.00,37.0,22.0,7.00,2.00,65.0,0.00,0.00,0.0,0.00,0.0,29.0,219.0,165.0,3.00,1.00,1.00,1.00,3.00,34.0,1.00,0.0,1.0,0.0,0.0,1.02,0.00,0.0,0.0,15.0,0.0,0.0,0.0,0.1,0.1,0.1,0.1,0.06,-0.1,-0.1,4.00,2.00,4.00,0.00,0.0,2.00,3.00,66.7,1.00,2.00,1.00,1.00,1.00,5.00,3.00,0.00,45.0,1.00,1.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,36.0,46.0,10.0,78.3,614.0,206.0,13.0,15.0,2.0,86.7,18.00,21.0,3.00,85.7,3.00,8.00,5.00,37.5,0.0,0.00,0.00,0.00,0.00,2.00,0.0,0.0,4.00,1.00,0.0,0.0,4.00,3.00,0.00,0.0,0.0,0.0,7.00,4.00,2.00,2.00,50.0,1.0,102.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Yunis Abdelhamid,MAR,DF,Saint-Étienne,Ligue 1,1987,37,11.0,58.3,11.50,37.6,19.5,1.27,0.64,58.3,0.64,0.27,42.9,0.36,57.1,29.3,157.5,76.1,0.36,0.09,0.00,0.73,0.27,35.7,0.27,0.0,2.0,1.0,50.0,0.18,0.09,0.0,0.0,10.8,0.0,0.0,0.0,0.2,0.018182,0.2,0.018182,0.12,-0.2,-0.2,1.55,1.00,1.36,0.18,0.0,0.91,1.45,62.5,0.55,2.36,1.64,0.73,1.18,2.73,5.18,0.09,42.0,3.85,1.83,0.0,0.0,0.00,0.28,0.0,0.0,0.0,0.0,0.18,0.09,39.8,45.9,6.1,86.7,722.9,218.5,13.4,14.5,1.1,91.9,23.90,26.1,2.20,91.6,2.09,4.36,2.27,47.9,0.0,0.01,0.03,-0.01,0.18,2.55,0.0,0.0,2.00,0.17,0.0,0.0,1.39,0.52,0.00,0.0,0.0,0.0,3.65,2.52,1.65,0.87,65.5,55.0,55.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
dftop.to_excel('df.xlsx', index=False)