<a href="https://colab.research.google.com/github/migueromrto-lab/repository/blob/main/CONCAT_TRANSF_FBREF_NOV25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
fbref = pd.read_csv('/content/FBREF_25_26_PER90_NOV_CLEAN.csv')

In [ ]:
transf = pd.read_csv('/content/Scrap_transf_NOV25.csv')

In [ ]:
fbref.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,G+A-PK,xG+xAG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,Dist,FK,npxG/Sh,G-xG,np:G-xG,Cmp,Att,Cmp%,TotDist,PrgDist,xA,A-xAG,KP,1/3,PPA,CrsPA,Live,Dead,FK_stats_passing_types,TB,Sw,Crs,TI,CK,In,Out,Str,Off,Blocks,SCA,SCA90,PassLive,PassDead,TO,Sh_stats_gca,Fld,Def,GCA,GCA90,Tkl,TklW,Def 3rd,Mid 3rd,Att 3rd,Att_stats_defense,Tkl%,Lost,Blocks_stats_defense,Sh_stats_defense,Pass,Int,Tkl+Int,Clr,Err,Touches,Def Pen,Def 3rd_stats_possession,Mid 3rd_stats_possession,Att 3rd_stats_possession,Att Pen,Live_stats_possession,Att_stats_possession,Succ,Succ%,Tkld,Tkld%,Carries,TotDist_stats_possession,PrgDist_stats_possession,1/3_stats_possession,CPA,Mis,Dis,Rec,Mn/MP,Min%,Mn/Start,Compl,Subs,Mn/Sub,unSub,PPM,onG,onGA,+/-,+/-90,On-Off,onxG,onxGA,xG+/-,xG+/-90,2CrdY,Fls,Fld_stats_misc,Off_stats_misc,PKwon,PKcon,OG,Recov,Won,Lost_stats_misc,Won%,MP_stats_keeper,Starts_stats_keeper,Min_stats_keeper,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm,FK_stats_keeper_adv,CK_stats_keeper_adv,OG_stats_keeper_adv,PSxG,PSxG/SoT,PSxG+/-,/90,Cmp_stats_keeper_adv,Att_stats_keeper_adv,Cmp%_stats_keeper_adv,Att (GK),Thr,Launch%,AvgLen,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist
0,Brenden Aaronson,USA,FW,Leeds United,Premier League,25,2000,11,8,711,7.9,0.126582,0.126582,0.253165,0.126582,0.000000,0.000000,0.126582,0.00000,0.21519,0.215190,0.164557,0.379747,2.151899,2.658228,4.810127,0.031646,0.048101,1.772152,0.632911,35.7,1.77,0.63,0.07,0.2,15.4,0.0,0.12,-0.088608,-0.088608,20.000000,24.556962,81.4,2227,499,0.177215,-0.037975,1.392405,12,1.139241,0.506329,22.278481,2.025316,0.253165,0.253165,0.000000,1.645570,0.632911,0.000000,0.00000,0.000000,0.0,0.253165,0.506329,3.291139,3.29,1.898734,0.000000,0.379747,0.632911,0.253165,0.126582,0.506329,0.51,2.531646,1.265823,1.139241,0.886076,0.506329,3.037975,50.0,1.518987,1.772152,0.126582,1.645570,0.886076,3.417722,1.265823,0.000000,40.632911,0.886076,7.215190,17.721519,16.455696,2.278481,40.632911,3.164557,1.139241,36.0,1.645570,52.0,21.772152,1087,512,10,0.253165,2.911392,2.151899,23.417722,65,71.8,79.0,0.126582,0.379747,27.0,0.000000,0.126582,1.265823,1.392405,-1,-0.13,0.351899,1.075949,1.341772,-2.0,-0.26,0.00000,0.506329,2.658228,0.126582,0.0,0.0,0.0,4.556962,0.506329,1.012658,33.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Jones El-Abdellaoui,MAR,MF,Celta Vigo,La Liga,19,2006,5,0,110,1.2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.75000,0.750000,0.083333,0.750000,10.000000,0.000000,22.500000,0.000000,0.641667,2.500000,0.000000,0.0,2.45,0.00,0.00,0.0,17.8,0.0,0.30,-0.750000,-0.750000,32.500000,42.500000,76.5,610,52,0.083333,-0.083333,1.666667,1,0.833333,0.833333,35.833333,6.666667,0.000000,0.000000,0.000000,8.333333,5.833333,0.000000,0.00000,0.000000,0.0,0.000000,3.333333,3.333333,3.27,3.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,1.666667,0.0,1.666667,0.000000,0.000000,0.000000,0.000000,0.000000,3.333333,0.000000,57.500000,0.833333,5.000000,16.666667,36.666667,3.333333,57.500000,5.833333,0.833333,14.3,3.333333,57.1,38.333333,404,242,4,2.500000,2.500000,0.833333,40.833333,22,10.2,0.0,0.000000,4.166667,22.0,5.833333,1.166667,2.500000,1.666667,1,0.82,0.991667,2.750000,2.333333,0.4,0.36,0.00000,0.833333,0.833333,0.000000,0.0,0.0,0.0,1.666667,1.666667,1.666667,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Himad Abdelli,ALG,MF,Angers,Ligue 1,26,1999,9,7,618,6.9,0.144928,0.000000,0.144928,0.000000,0.144928,0.144928,0.000000,0.00000,0.15942,0.043478,0.043478,0.086957,3.623188,7.391304,1.594203,0.000000,0.030435,0.724638,0.144928,20.0,0.73,0.15,0.00,0.0,23.2,0.0,0.07,-0.014493,-0.043478,48.260870,56.376812,85.6,5631,1582,0.072464,-0.043478,0.724638,30,1.304348,0.000000,53.188406,3.188406,1.014493,0.434783,0.144928,1.159420,0.724638,0.724638,0.57971,0.144928,0.0,0.000000,0.579710,2.898551,2.91,2.028986,0.434783,0.289855,0.144928,0.000000,0.000000,0.289855,0.29,1.739130,1.159420,0.869565,0.724638,0.144928,1.594203,81.8,0.289855,2.028986,0.434783,1.594203,1.159420,2.898551,0.869565,0.144928,68.840580,1.739130,17.681159,41.159420,11.159420,1.014493,68.695652,2.898551,1.304348,45.0,1.594203,55.0,36.956522,1507,928,21,0.000000,1.884058,1.159420,48.840580,69,57.2,81.0,0.434783,0.289855,25.0,0.000000,0.144928,1.014493,1.594203,-4,-0.58,-0.056522,1.043478,2.101449,-7.3,-1.07,0.00000,1.594203,0.724638,0.144928,0.0,0.0,0.0,5.507246,0.869565,0.289855,75.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Ali Abdi,TUN,DF,Nice,Ligue 1,31,1993,5,5,300,3.3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.606061,0.30303,0.00000,0.000000,0.121212,0.121212,1.818182,0.606061,3.333333,0.000000,0.036364,0.000000,0.000000,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.000000,0.000000,20.000000,26.969697,74.2,902,337,0.060606,-0.121212,1.212121,6,0.909091,0.303030,20.909091,6.060606,0.909091,0.000000,0.000000,1.515152,5.151515,0.000000,0.00000,0.000000,0.0,0.000000,1.818182,1.212121,1.27,1.212121,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,2.121212,0.303030,1.515152,0.303030,0.303030,0.606061,0.0,0.606061,0.303030,0.000000,0.303030,0.909091,3.030303,2.121212,0.000000,38.181818,2.424242,11.818182,15.454545,11.212121,0.909091,38.181818,2.727273,0.909091,33.3,1.515152,55.6,17.272727,327,154,1,0.303030,2.424242,0.000000,19.696970,60,27.8,60.0,0.303030,0.000000,0.0,0.303030,0.303030,1.515152,0.606061,3,0.90,0.412121,0.757576,1.151515,-1.3,-0.40,0.30303,1.818182,1.818182,0.000000,0.0,0.0,0.0,3.939394,0.909091,1.818182,33.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Salis Abdul Samed,GHA,MF,Nice,Ligue 1,25,2000,8,5,352,3.9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.256410,0.00000,0.00000,0.000000,0.000000,0.000000,0.512821,1.025641,0.769231,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.000000,0.000000,37.179487,40.769231,91.2,1975,438,0.025641,0.000000,0.000000,8,0.000000,0.000000,39.743590,1.025641,1.025641,0.256410,0.000000,0.256410,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.512821,0.512821,0.51,0.512821,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.769231,0.256410,0.769231,0.000000,0.000000,0.769231,66.7,0.256410,0.512821,0.000000,0.512821,1.282051,2.051282,0.512821,0.000000,46.923077,1.538462,12.051282,30.256410,4.615385,0.512821,46.923077,0.769231,0.256410,33.3,0.512821,66.7,28.461538,529,217,2,0.256410,1.025641,1.025641,33.846154,44,32.6,62.0,0.000000,0.769231,14.0,1.025641,0.353846,1.794872,1.282051,2,0.51,0.225641,0.948718,1.538462,-2.2,-0.58,0.00000,1.282051,1.282051,0.000000,0.0,0.0,0.0,2.820513,0.769231,0.769231,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# prompt: cambiar las comas por puntos en TODAS las columnas, para que sean numéricas

for col in fbref.columns:
  if fbref[col].dtype == 'object':
    try:
      fbref[col] = fbref[col].str.replace(',', '.').astype(float)
    except ValueError:
      pass # Keep the column as is if conversion fails
fbref.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,G+A-PK,xG+xAG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,Dist,FK,npxG/Sh,G-xG,np:G-xG,Cmp,Att,Cmp%,TotDist,PrgDist,xA,A-xAG,KP,1/3,PPA,CrsPA,Live,Dead,FK_stats_passing_types,TB,Sw,Crs,TI,CK,In,Out,Str,Off,Blocks,SCA,SCA90,PassLive,PassDead,TO,Sh_stats_gca,Fld,Def,GCA,GCA90,Tkl,TklW,Def 3rd,Mid 3rd,Att 3rd,Att_stats_defense,Tkl%,Lost,Blocks_stats_defense,Sh_stats_defense,Pass,Int,Tkl+Int,Clr,Err,Touches,Def Pen,Def 3rd_stats_possession,Mid 3rd_stats_possession,Att 3rd_stats_possession,Att Pen,Live_stats_possession,Att_stats_possession,Succ,Succ%,Tkld,Tkld%,Carries,TotDist_stats_possession,PrgDist_stats_possession,1/3_stats_possession,CPA,Mis,Dis,Rec,Mn/MP,Min%,Mn/Start,Compl,Subs,Mn/Sub,unSub,PPM,onG,onGA,+/-,+/-90,On-Off,onxG,onxGA,xG+/-,xG+/-90,2CrdY,Fls,Fld_stats_misc,Off_stats_misc,PKwon,PKcon,OG,Recov,Won,Lost_stats_misc,Won%,MP_stats_keeper,Starts_stats_keeper,Min_stats_keeper,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm,FK_stats_keeper_adv,CK_stats_keeper_adv,OG_stats_keeper_adv,PSxG,PSxG/SoT,PSxG+/-,/90,Cmp_stats_keeper_adv,Att_stats_keeper_adv,Cmp%_stats_keeper_adv,Att (GK),Thr,Launch%,AvgLen,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist
0,Brenden Aaronson,USA,FW,Leeds United,Premier League,25,2000,11,8,711,7.9,0.126582,0.126582,0.253165,0.126582,0.000000,0.000000,0.126582,0.00000,0.21519,0.215190,0.164557,0.379747,2.151899,2.658228,4.810127,0.031646,0.048101,1.772152,0.632911,35.7,1.77,0.63,0.07,0.2,15.4,0.0,0.12,-0.088608,-0.088608,20.000000,24.556962,81.4,2227,499,0.177215,-0.037975,1.392405,12,1.139241,0.506329,22.278481,2.025316,0.253165,0.253165,0.000000,1.645570,0.632911,0.000000,0.00000,0.000000,0.0,0.253165,0.506329,3.291139,3.29,1.898734,0.000000,0.379747,0.632911,0.253165,0.126582,0.506329,0.51,2.531646,1.265823,1.139241,0.886076,0.506329,3.037975,50.0,1.518987,1.772152,0.126582,1.645570,0.886076,3.417722,1.265823,0.000000,40.632911,0.886076,7.215190,17.721519,16.455696,2.278481,40.632911,3.164557,1.139241,36.0,1.645570,52.0,21.772152,1087,512,10,0.253165,2.911392,2.151899,23.417722,65,71.8,79.0,0.126582,0.379747,27.0,0.000000,0.126582,1.265823,1.392405,-1,-0.13,0.351899,1.075949,1.341772,-2.0,-0.26,0.00000,0.506329,2.658228,0.126582,0.0,0.0,0.0,4.556962,0.506329,1.012658,33.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Jones El-Abdellaoui,MAR,MF,Celta Vigo,La Liga,19,2006,5,0,110,1.2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.75000,0.750000,0.083333,0.750000,10.000000,0.000000,22.500000,0.000000,0.641667,2.500000,0.000000,0.0,2.45,0.00,0.00,0.0,17.8,0.0,0.30,-0.750000,-0.750000,32.500000,42.500000,76.5,610,52,0.083333,-0.083333,1.666667,1,0.833333,0.833333,35.833333,6.666667,0.000000,0.000000,0.000000,8.333333,5.833333,0.000000,0.00000,0.000000,0.0,0.000000,3.333333,3.333333,3.27,3.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,1.666667,0.0,1.666667,0.000000,0.000000,0.000000,0.000000,0.000000,3.333333,0.000000,57.500000,0.833333,5.000000,16.666667,36.666667,3.333333,57.500000,5.833333,0.833333,14.3,3.333333,57.1,38.333333,404,242,4,2.500000,2.500000,0.833333,40.833333,22,10.2,0.0,0.000000,4.166667,22.0,5.833333,1.166667,2.500000,1.666667,1,0.82,0.991667,2.750000,2.333333,0.4,0.36,0.00000,0.833333,0.833333,0.000000,0.0,0.0,0.0,1.666667,1.666667,1.666667,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Himad Abdelli,ALG,MF,Angers,Ligue 1,26,1999,9,7,618,6.9,0.144928,0.000000,0.144928,0.000000,0.144928,0.144928,0.000000,0.00000,0.15942,0.043478,0.043478,0.086957,3.623188,7.391304,1.594203,0.000000,0.030435,0.724638,0.144928,20.0,0.73,0.15,0.00,0.0,23.2,0.0,0.07,-0.014493,-0.043478,48.260870,56.376812,85.6,5631,1582,0.072464,-0.043478,0.724638,30,1.304348,0.000000,53.188406,3.188406,1.014493,0.434783,0.144928,1.159420,0.724638,0.724638,0.57971,0.144928,0.0,0.000000,0.579710,2.898551,2.91,2.028986,0.434783,0.289855,0.144928,0.000000,0.000000,0.289855,0.29,1.739130,1.159420,0.869565,0.724638,0.144928,1.594203,81.8,0.289855,2.028986,0.434783,1.594203,1.159420,2.898551,0.869565,0.144928,68.840580,1.739130,17.681159,41.159420,11.159420,1.014493,68.695652,2.898551,1.304348,45.0,1.594203,55.0,36.956522,1507,928,21,0.000000,1.884058,1.159420,48.840580,69,57.2,81.0,0.434783,0.289855,25.0,0.000000,0.144928,1.014493,1.594203,-4,-0.58,-0.056522,1.043478,2.101449,-7.3,-1.07,0.00000,1.594203,0.724638,0.144928,0.0,0.0,0.0,5.507246,0.869565,0.289855,75.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Ali Abdi,TUN,DF,Nice,Ligue 1,31,1993,5,5,300,3.3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.606061,0.30303,0.00000,0.000000,0.121212,0.121212,1.818182,0.606061,3.333333,0.000000,0.036364,0.000000,0.000000,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.000000,0.000000,20.000000,26.969697,74.2,902,337,0.060606,-0.121212,1.212121,6,0.909091,0.303030,20.909091,6.060606,0.909091,0.000000,0.000000,1.515152,5.151515,0.000000,0.00000,0.000000,0.0,0.000000,1.818182,1.212121,1.27,1.212121,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,2.121212,0.303030,1.515152,0.303030,0.303030,0.606061,0.0,0.606061,0.303030,0.000000,0.303030,0.909091,3.030303,2.121212,0.000000,38.181818,2.424242,11.818182,15.454545,11.212121,0.909091,38.181818,2.727273,0.909091,33.3,1.515152,55.6,17.272727,327,154,1,0.303030,2.424242,0.000000,19.696970,60,27.8,60.0,0.303030,0.000000,0.0,0.303030,0.303030,1.515152,0.606061,3,0.90,0.412121,0.757576,1.151515,-1.3,-0.40,0.30303,1.818182,1.818182,0.000000,0.0,0.0,0.0,3.939394,0.909091,1.818182,33.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Salis Abdul Samed,GHA,MF,Nice,Ligue 1,25,2000,8,5,352,3.9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.256410,0.00000,0.00000,0.000000,0.000000,0.000000,0.512821,1.025641,0.769231,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.000000,0.000000,37.179487,40.769231,91.2,1975,438,0.025641,0.000000,0.000000,8,0.000000,0.000000,39.743590,1.025641,1.025641,0.256410,0.000000,0.256410,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.512821,0.512821,0.51,0.512821,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.769231,0.256410,0.769231,0.000000,0.000000,0.769231,66.7,0.256410,0.512821,0.000000,0.512821,1.282051,2.051282,0.512821,0.000000,46.923077,1.538462,12.051282,30.256410,4.615385,0.512821,46.923077,0.769231,0.256410,33.3,0.512821,66.7,28.461538,529,217,2,0.256410,1.025641,1.025641,33.846154,44,32.6,62.0,0.000000,0.769231,14.0,1.025641,0.353846,1.794872,1.282051,2,0.51,0.225641,0.948718,1.538462,-2.2,-0.58,0.00000,1.282051,1.282051,0.000000,0.0,0.0,0.0,2.820513,0.769231,0.769231,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Identificar las columnas a convertir a numérica
cols_to_convert = fbref.columns[5:]

# Convertir las columnas
for col in cols_to_convert:
    fbref[col] = pd.to_numeric(fbref[col], errors='coerce')

In [ ]:
transf.dtypes

Jugadores                 object
Posicion                  object
Fecha de nac.             object
Altura                   float64
Pie                       object
Contrato                  object
Pais                      object
Seg nacionalidad          object
equipo                    object
Valor de mercado (M€)    float64
dtype: object

In [ ]:
transf.columns

Index(['Jugadores', 'Posicion', 'Fecha de nac.', 'Altura', 'Pie', 'Contrato',
       'Pais', 'Seg nacionalidad', 'equipo', 'Valor de mercado (M€)'],
      dtype='object')

In [ ]:
fbref.columns

Index(['Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'Born', 'MP',
       'Starts', 'Min',
       ...
       'Att (GK)', 'Thr', 'Launch%', 'AvgLen', 'Opp', 'Stp', 'Stp%', '#OPA',
       '#OPA/90', 'AvgDist'],
      dtype='object', length=174)

In [ ]:
transf = transf.drop(columns=["Fecha de nac."], errors="ignore")

In [ ]:
transf.head()

,Jugadores,Posicion,Altura,Pie,Contrato,Pais,Seg nacionalidad,equipo,Valor de mercado (M€)
0,Thibaut Courtois,Portero,2.00,Izquierdo,30/06/2027,Bélgica,NaN,Real Madrid,20.0
1,Andriy Lunin,Portero,1.91,Derecho,30/06/2030,Ucrania,NaN,Real Madrid,18.0
2,Dean Huijsen,Defensa central,1.97,Ambidiestro,30/06/2030,España,Países Bajos,Real Madrid,70.0
3,Éder Militão,Defensa central,1.86,Derecho,30/06/2028,Brasil,España,Real Madrid,30.0
4,Raúl Asencio,Defensa central,1.84,Derecho,30/06/2031,España,NaN,Real Madrid,30.0

In [ ]:
len(fbref)

2275

In [ ]:
!pip install rapidfuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 27.9 MB/s eta 0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.3

In [ ]:
# Limpiar strings
fbref['Player'] = fbref['Player'].astype(str).str.strip()
fbref['Squad'] = fbref['Squad'].astype(str).str.strip()
transf['Jugadores'] = transf['Jugadores'].astype(str).str.strip()
transf['equipo'] = transf['equipo'].astype(str).str.strip()

In [ ]:
from rapidfuzz import process, fuzz
import pandas as pd

# --- PRIMERA FASE: Match por nombre con umbral alto (≥75) ---
nombres_transf = transf['Jugadores'].tolist()

def fuzzy_match_nombre(nombre, lista_objetivo, umbral=75):
    resultado = process.extractOne(nombre, lista_objetivo, scorer=fuzz.token_sort_ratio)
    if resultado and resultado[1] >= umbral:
        return resultado[0], resultado[1]
    return None, resultado[1] if resultado else 0

fbref[['MatchTransf', 'MatchScore']] = fbref['Player'].apply(
    lambda x: pd.Series(fuzzy_match_nombre(x, nombres_transf, umbral=75))
)

# --- SEGUNDA FASE: para los que no han hecho match (MatchScore < 75) ---
# Crea tuplas con (nombre, equipo) de transf
transf_tuplas = list(zip(transf['Jugadores'], transf['equipo']))

# Matching combinado para los casos dudosos
def fuzzy_match_nombre_y_equipo(nombre_fbref, equipo_fbref, transf_tuplas, umbral_nombre=60, umbral_equipo=60):
    mejores = []
    for nombre_t, equipo_t in transf_tuplas:
        score_n = fuzz.token_sort_ratio(nombre_fbref, nombre_t)
        score_e = fuzz.token_sort_ratio(equipo_fbref, equipo_t)
        if score_n >= umbral_nombre and score_e >= umbral_equipo:
            mejores.append((nombre_t, score_n, score_e))
    if mejores:
        mejores.sort(key=lambda x: (x[1] + x[2]), reverse=True)
        return mejores[0][0], mejores[0][1], mejores[0][2]
    return None, 0, 0

# Aplicar solo a los que no fueron emparejados en la primera fase
fbref_dudosos = fbref[fbref['MatchScore'] < 75].copy()

fbref_dudosos[['MatchTransf_alt', 'ScoreNombre_alt', 'ScoreEquipo_alt']] = fbref_dudosos.apply(
    lambda row: pd.Series(fuzzy_match_nombre_y_equipo(row['Player'], row['Squad'], transf_tuplas)),
    axis=1
)

# Rellenar las coincidencias encontradas en esta segunda fase
fbref.loc[fbref['MatchScore'] < 75, 'MatchTransf'] = fbref_dudosos['MatchTransf_alt']
fbref.loc[fbref['MatchScore'] < 75, 'MatchScore'] = fbref_dudosos['ScoreNombre_alt']
fbref.loc[fbref['MatchScore'] < 75, 'ScoreEquipo'] = fbref_dudosos['ScoreEquipo_alt']

# Filtrar jugadores con match
fbref_matcheados = fbref[fbref['MatchTransf'].notna()].copy()

# Merge final con transf
df_merged = pd.merge(
    fbref_matcheados,
    transf,
    left_on='MatchTransf',
    right_on='Jugadores',
    how='left'
)

df_merged.drop(columns=['Jugadores'], inplace=True)
print(f"✅ Total emparejados: {df_merged.shape[0]} jugadores")

# (Opcional) ver los peores matches
df_merged.sort_values(by='MatchScore').head(5)

✅ Total emparejados: 2117 jugadores

/tmp/ipython-input-876203496.py:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  fbref.loc[fbref['MatchScore'] < 75, 'ScoreEquipo'] = fbref_dudosos['ScoreEquipo_alt']

,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,G+A-PK,xG+xAG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,Dist,FK,npxG/Sh,G-xG,np:G-xG,Cmp,Att,Cmp%,TotDist,PrgDist,xA,A-xAG,KP,1/3,PPA,CrsPA,Live,Dead,FK_stats_passing_types,TB,Sw,Crs,TI,CK,In,Out,Str,Off,Blocks,SCA,SCA90,PassLive,PassDead,TO,Sh_stats_gca,Fld,Def,GCA,GCA90,Tkl,TklW,Def 3rd,Mid 3rd,Att 3rd,Att_stats_defense,Tkl%,Lost,Blocks_stats_defense,Sh_stats_defense,Pass,Int,Tkl+Int,Clr,Err,Touches,Def Pen,Def 3rd_stats_possession,Mid 3rd_stats_possession,Att 3rd_stats_possession,Att Pen,Live_stats_possession,Att_stats_possession,Succ,Succ%,Tkld,Tkld%,Carries,TotDist_stats_possession,PrgDist_stats_possession,1/3_stats_possession,CPA,Mis,Dis,Rec,Mn/MP,Min%,Mn/Start,Compl,Subs,Mn/Sub,unSub,PPM,onG,onGA,+/-,+/-90,On-Off,onxG,onxGA,xG+/-,xG+/-90,2CrdY,Fls,Fld_stats_misc,Off_stats_misc,PKwon,PKcon,OG,Recov,Won,Lost_stats_misc,Won%,MP_stats_keeper,Starts_stats_keeper,Min_stats_keeper,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm,FK_stats_keeper_adv,CK_stats_keeper_adv,OG_stats_keeper_adv,PSxG,PSxG/SoT,PSxG+/-,/90,Cmp_stats_keeper_adv,Att_stats_keeper_adv,Cmp%_stats_keeper_adv,Att (GK),Thr,Launch%,AvgLen,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist,MatchTransf,MatchScore,ScoreEquipo,Posicion,Altura,Pie,Contrato,Pais,Seg nacionalidad,equipo,Valor de mercado (M€)
277,Gleison Bremer,BRA,DF,Juventus,Serie A,28,1997,4,4,345,3.8,0.0,0.526316,0.526316,0.0,0.0,0.0,0.000000,0.0,0.078947,0.078947,0.026316,0.105263,0.000000,1.052632,0.526316,0.136842,0.031579,1.052632,0.263158,25.0,1.04,0.26,0.0,0.0,15.3,0.000000,0.08,-0.078947,-0.078947,44.473684,52.105263,85.4,3441,1116,0.026316,0.500000,0.789474,4,0.000000,0.000000,50.789474,1.315789,0.526316,0.263158,0.526316,0.263158,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.052632,1.052632,1.04,1.052632,0.000000,0.0,0.000000,0.000000,0.0,0.526316,0.52,0.526316,0.263158,0.263158,0.263158,0.000000,0.263158,100.0,0.000000,0.789474,0.526316,0.263158,0.526316,1.052632,5.789474,0.000000,64.210526,7.368421,34.473684,25.000000,4.736842,1.578947,64.210526,0.263158,0.000000,0.0,0.263158,100.0,36.578947,643,208,1,0.000000,0.789474,0.000000,41.842105,86,34.8,86.0,0.789474,0.000000,0.0,0.263158,0.657895,1.842105,1.052632,3,0.78,0.168421,1.184211,0.736842,1.7,0.44,0.0,0.526316,0.789474,0.000000,0.0,0.0,0.0,4.736842,1.842105,2.631579,41.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bremer,60.000000,84.210526,Defensa central,1.88,Derecho,30/06/2029,Brasil,NaN,Juventus FC,50.0
320,Duje Ćaleta-Car,CRO,DF,Real Sociedad,La Liga,29,1996,8,8,697,7.7,0.0,0.000000,0.000000,0.0,0.0,0.0,0.389610,0.0,0.051948,0.051948,0.012987,0.077922,1.168831,3.376623,0.129870,0.000000,0.009091,0.519481,0.129870,25.0,0.52,0.13,0.0,0.0,9.1,0.000000,0.10,-0.051948,-0.051948,52.987013,58.051948,91.3,7791,2980,0.064935,-0.012987,0.389610,32,0.259740,0.000000,55.844156,2.207792,1.558442,0.259740,0.519481,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.909091,0.90,0.909091,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.00,0.519481,0.259740,0.259740,0.259740,0.000000,0.389610,66.7,0.129870,1.038961,0.909091,0.129870,1.038961,1.558442,4.285714,0.000000,67.272727,7.662338,30.129870,35.584416,1.818182,1.168831,67.272727,0.000000,0.000000,0.0,0.000000,0.0,39.090909,1590,1056,5,0.000000,0.129870,0.000000,45.324675,87,64.5,87.0,0.909091,0.000000,0.0,0.519481,0.081818,0.779221,1.428571,-5,-0.65,-0.145455,1.363636,1.402597,-0.3,-0.04,0.0,1.428571,0.259740,0.129870,0.0,0.0,0.0,4.025974,2.727273,1.558442,63.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Duje Caleta-Car,60.000000,100.000000,Defensa central,1.93,Derecho,30/06/2026,Croacia,NaN,Real Sociedad,4.0
62,Domingos André Ribeiro Almeida,POR,MF,Valencia,La Liga,25,2000,6,2,239,2.7,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.037037,0.037037,0.185185,0.259259,2.962963,8.148148,3.703704,0.000000,0.092593,1.111111,0.370370,33.3,1.13,0.38,0.0,0.0,21.0,0.000000,0.04,-0.037037,-0.037037,42.962963,52.962963,81.1,2094,526,0.074074,-0.185185,0.740741,13,1.851852,0.000000,48.518519,4.444444,1.481481,0.370370,0.370370,4.074074,0.000000,2.592593,1.481481,0.740741,0.0,0.000000,1.111111,3.703704,3.77,3.333333,0.000000,0.0,0.370370,0.000000,0.0,0.370370,0.38,2.222222,0.740741,1.481481,0.740741,0.000000,1.851852,80.0,0.370370,1.481481,0.000000,1.481481,1.111111,3.333333,0.370370,0.000000,62.222222,1.481481,9.259259,32.222222,21.481481,0.370370,62.222222,2.962963,1.111111,37.5,1.111111,37.5,41.851852,722,354,5,0.000000,0.740741,1.481481,47.777778,40,22.1,65.0,0.000000,1.481481,27.0,1.851852,0.307407,0.740741,0.740741,0,0.00,0.396296,1.814815,1.111111,2.0,0.73,0.0,0.370370,3.333333,0.000000,0.0,0.0,0.0,4.444444,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,André Almeida,60.465116,84.210526,Mediocentro ofensivo,1.76,Derecho,30/06/2029,Portugal,NaN,Valencia CF,10.0
1516,Emerson Palmieri,ITA,DF,Marseille,Ligue 1,31,1994,9,7,667,7.4,0.0,0.135135,0.135135,0.0,0.0,0.0,0.135135,0.0,0.027027,0.027027,0.189189,0.216216,1.891892,5.945946,2.972973,0.017568,0.028378,0.675676,0.135135,20.0,0.67,0.13,0.0,0.0,24.3,0.135135,0.04,-0.027027,-0.027027,63.918919,72.972973,87.6,6871,2097,0.202703,-0.054054,1.486486,37,0.540541,0.135135,65.405405,7.432432,1.891892,0.270270,0.000000,4.459459,3.648649,1.891892,0.540541,1.216216,0.0,0.135135,0.810811,2.702703,2.70,1.621622,1.081081,0.0,0.000000,0.000000,0.0,0.135135,0.13,2.162162,1.486486,0.945946,0.675676,0.540541,2.162162,87.5,0.270270,0.810811,0.270270,0.540541,1.621622,3.783784,2.162162,0.135135,82.702703,3.243243,16.486486,43.378378,23.243243,0.945946,82.702703,1.081081,0.270270,25.0,0.810811,75.0,55.000000,1741,873,12,0.000000,0.810811,0.540541,59.729730,74,61.8,86.0,0.810811,0.270270,32.0,0.000000,0.329730,2.027027,0.675676,10,1.35,-0.024324,1.743243,0.891892,6.4,0.86,0.0,1.081081,0.135135,0.135135,0.0,0.0,0.0,2.972973,0.810811,0.540541,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Emerson,60.869565,64.285714,Lateral izquierdo,1.76,Izquierdo,30/06/2027,Italia,Brasil,Olympique Marseille,10.0
1732,Mbwana Samatta,TAN,FW,Le Havre,Ligue 1,32,1992,8,7,513,5.7,0.0,0.000000,0.000000,0.0,0.0,0.0,0.350877,0.0,0.210526,0.210526,0.052632,0.280702,1.052632,1.578947,5.263158,0.000000,0.049123,2.456140,0.701754,28.6,2.46,0.70,0.0,0.0,14.0,0.000000,0.09,-0.210526,-0.210526,11.578947,16.491228,70.2,1003,218,0.105263,-0.052632,1.052632,3,0.350877,0.000000,15.263158,1.228070,0.000000,0.175439,0.175439,0.350877,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.877193,1.929825,1.93,1.228070,0.000000,0.0,0.350877,0.350877,0.0,0.000000,0.00,0.350877,0.175439,0.000000,0.175439,0.175439,0.877193,20.0,0.701754,0.526316,0.000000,0.526316,0.175439,0.526316,0.000000,0.000000,27.368421,0.175439,0.701754,14.210526,12.982456,4.912281,27.368421,1.578947,0.701754,44.4,0.526316,33.3,14.385965,434,135,3,0.175439,3.684211,1.754386,19.473684,64,47.5,69.0,0.175439,0.175439,33.0,0.000000,0.175439,1.228070,1.403509,-1,-0.18,0.052632,1.403509,1.157895,1.4,0.25,0.0,1.929825,1.052632,0.526316,0.0,0.0,0.0,1.929825,2.456140,2.982456,45.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ally Samatta,61.538462,84.210526,Delantero centro,1.83,Derecho,30/06/2026,Tanzania,NaN,Le Havre AC,0.9

In [ ]:
# QUITAMOS DUPLICADOS: mismo MatchTransf emparejado a varios jugadores fbref
# Nos quedamos con el de mayor MatchScore
fbref_final = fbref[fbref['MatchTransf'].notna()].copy()

# Ordenar para que el mejor match quede primero
fbref_final = fbref_final.sort_values(by='MatchScore', ascending=False)

# Eliminar duplicados en MatchTransf (conservando el mejor match)
fbref_final = fbref_final.drop_duplicates(subset='MatchTransf', keep='first')

In [ ]:
df_merged = pd.merge(
    fbref_final,
    transf,
    left_on='MatchTransf',
    right_on='Jugadores',
    how='left'
)
df_merged.drop(columns=['Jugadores'], inplace=True)
print(f"✅ Emparejamientos únicos: {df_merged.shape[0]} jugadores")

✅ Emparejamientos únicos: 2043 jugadores

In [ ]:
df_merged.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,G+A-PK,xG+xAG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,Dist,FK,npxG/Sh,G-xG,np:G-xG,Cmp,Att,Cmp%,TotDist,PrgDist,xA,A-xAG,KP,1/3,PPA,CrsPA,Live,Dead,FK_stats_passing_types,TB,Sw,Crs,TI,CK,In,Out,Str,Off,Blocks,SCA,SCA90,PassLive,PassDead,TO,Sh_stats_gca,Fld,Def,GCA,GCA90,Tkl,TklW,Def 3rd,Mid 3rd,Att 3rd,Att_stats_defense,Tkl%,Lost,Blocks_stats_defense,Sh_stats_defense,Pass,Int,Tkl+Int,Clr,Err,Touches,Def Pen,Def 3rd_stats_possession,Mid 3rd_stats_possession,Att 3rd_stats_possession,Att Pen,Live_stats_possession,Att_stats_possession,Succ,Succ%,Tkld,Tkld%,Carries,TotDist_stats_possession,PrgDist_stats_possession,1/3_stats_possession,CPA,Mis,Dis,Rec,Mn/MP,Min%,Mn/Start,Compl,Subs,Mn/Sub,unSub,PPM,onG,onGA,+/-,+/-90,On-Off,onxG,onxGA,xG+/-,xG+/-90,2CrdY,Fls,Fld_stats_misc,Off_stats_misc,PKwon,PKcon,OG,Recov,Won,Lost_stats_misc,Won%,MP_stats_keeper,Starts_stats_keeper,Min_stats_keeper,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm,FK_stats_keeper_adv,CK_stats_keeper_adv,OG_stats_keeper_adv,PSxG,PSxG/SoT,PSxG+/-,/90,Cmp_stats_keeper_adv,Att_stats_keeper_adv,Cmp%_stats_keeper_adv,Att (GK),Thr,Launch%,AvgLen,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist,MatchTransf,MatchScore,ScoreEquipo,Posicion,Altura,Pie,Contrato,Pais,Seg nacionalidad,equipo,Valor de mercado (M€)
0,Martin Ødegaard,NOR,MF,Arsenal,Premier League,26,1998,6,4,203,2.3,0.000000,0.434783,0.434783,0.000000,0.0,0.0,0.000000,0.0,0.043478,0.043478,0.217391,0.260870,4.347826,11.304348,2.173913,0.191304,0.117391,1.739130,0.434783,25.0,1.77,0.44,0.00,0.0,21.7,0.000000,0.04,-0.043478,-0.043478,48.260870,60.869565,79.3,1924,646,0.347826,0.217391,1.304348,19,3.913043,0.000000,56.956522,3.478261,1.304348,1.739130,0.0,2.173913,0.434783,0.869565,0.869565,0.0,0.0,0.434783,1.304348,4.782609,4.88,2.608696,0.434783,0.869565,0.434783,0.434783,0.000000,1.304348,1.33,1.304348,0.434783,0.434783,0.000000,0.869565,0.434783,100.0,0.000000,0.000000,0.000000,0.000000,0.434783,1.739130,2.173913,0.0,69.565217,1.304348,8.695652,34.782609,26.956522,1.739130,69.565217,2.173913,1.304348,60.0,0.869565,40.0,44.782609,800,436,10,0.869565,0.869565,0.000000,50.869565,34,20.5,43.0,0.434783,0.869565,15.0,0.000000,1.086957,1.739130,0.434783,3,1.33,-0.017391,1.608696,1.000000,1.4,0.63,0.0,0.869565,1.304348,0.000000,0.0,0.0,0.0,4.347826,0.434783,0.434783,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Martin Ødegaard,100.0,NaN,Mediocentro ofensivo,1.78,Izquierdo,30/06/2028,Noruega,NaN,Arsenal FC,80.0
1,Brenden Aaronson,USA,FW,Leeds United,Premier League,25,2000,11,8,711,7.9,0.126582,0.126582,0.253165,0.126582,0.0,0.0,0.126582,0.0,0.215190,0.215190,0.164557,0.379747,2.151899,2.658228,4.810127,0.031646,0.048101,1.772152,0.632911,35.7,1.77,0.63,0.07,0.2,15.4,0.000000,0.12,-0.088608,-0.088608,20.000000,24.556962,81.4,2227,499,0.177215,-0.037975,1.392405,12,1.139241,0.506329,22.278481,2.025316,0.253165,0.253165,0.0,1.645570,0.632911,0.000000,0.000000,0.0,0.0,0.253165,0.506329,3.291139,3.29,1.898734,0.000000,0.379747,0.632911,0.253165,0.126582,0.506329,0.51,2.531646,1.265823,1.139241,0.886076,0.506329,3.037975,50.0,1.518987,1.772152,0.126582,1.645570,0.886076,3.417722,1.265823,0.0,40.632911,0.886076,7.215190,17.721519,16.455696,2.278481,40.632911,3.164557,1.139241,36.0,1.645570,52.0,21.772152,1087,512,10,0.253165,2.911392,2.151899,23.417722,65,71.8,79.0,0.126582,0.379747,27.0,0.000000,0.126582,1.265823,1.392405,-1,-0.13,0.351899,1.075949,1.341772,-2.0,-0.26,0.0,0.506329,2.658228,0.126582,0.0,0.0,0.0,4.556962,0.506329,1.012658,33.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Brenden Aaronson,100.0,NaN,Mediocentro ofensivo,1.77,Derecho,30/06/2027,Estados Unidos,NaN,Leeds United,15.0
2,Jordan Zemura,ZIM,DF,Udinese,Serie A,26,1999,6,4,373,4.1,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.243902,0.0,0.024390,0.024390,0.024390,0.048780,1.707317,2.195122,6.585366,0.000000,0.014634,0.487805,0.000000,0.0,0.48,0.00,0.00,0.0,24.0,0.243902,0.07,-0.024390,-0.024390,28.292683,40.243902,70.3,1891,736,0.048780,-0.024390,0.731707,10,1.463415,0.731707,29.512195,10.731707,1.951220,0.000000,0.0,4.634146,8.780488,0.000000,0.000000,0.0,0.0,0.000000,2.195122,1.951220,1.93,1.707317,0.000000,0.000000,0.000000,0.243902,0.000000,0.487805,0.48,1.463415,0.731707,0.975610,0.487805,0.000000,2.195122,33.3,1.463415,0.487805,0.000000,0.487805,0.487805,1.951220,3.658537,0.0,52.439024,1.463415,13.170732,20.487805,19.268293,1.463415,52.439024,1.707317,0.243902,14.3,1.463415,85.7,23.658537,535,271,7,0.243902,2.195122,0.975610,28.536585,62,37.7,87.0,0.731707,0.487805,13.0,1.219512,0.285366,0.975610,1.951220,-4,-0.97,-0.200000,0.926829,1.243902,-1.3,-0.32,0.0,0.975610,0.975610,0.487805,0.0,0.0,0.0,2.682927,0.487805,1.219512,28.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Jordan Zemura,100.0,NaN,Lateral izquierdo,1.73,Izquierdo,30/06/2027,Zimbabue,Inglaterra,Udinese Calcio,4.5
3,Aaron Zehnter,GER,DF,Wolfsburg,Bundesliga,21,2004,7,6,539,6.0,0.166667,0.000000,0.166667,0.166667,0.0,0.0,0.000000,0.0,0.050000,0.050000,0.066667,0.116667,1.500000,1.500000,3.000000,0.028333,0.018333,0.833333,0.333333,40.0,0.83,0.33,0.20,0.5,21.4,0.000000,0.05,0.116667,0.116667,38.833333,49.666667,78.2,4337,1327,0.066667,-0.066667,1.000000,10,0.333333,0.000000,40.333333,9.000000,0.666667,0.166667,0.0,1.333333,8.166667,0.166667,0.166667,0.0,0.0,0.333333,1.666667,1.666667,1.67,1.166667,0.333333,0.166667,0.000000,0.000000,0.000000,0.166667,0.17,0.500000,0.333333,0.333333,0.166667,0.000000,0.833333,40.0,0.500000,1.166667,0.666667,0.500000,1.666667,2.166667,2.666667,0.0,57.166667,3.666667,23.500000,21.833333,12.166667,1.000000,57.166667,0.500000,0.500000,100.0,0.000000,0.0,29.500000,706,403,9,0.333333,0.500000,0.000000,31.666667,77,59.9,90.0,0.666667,0.166667,1.0,0.500000,0.166667,1.333333,1.666667,-2,-0.33,0.110000,1.000000,1.633333,-3.8,-0.63,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,4.333333,0.500000,0.500000,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Aaron Zehnter,100.0,NaN,Lateral izquierdo,1.80,Izquierdo,30/06/2030,Alemania,NaN,VfL Wolfsburg,6.0
4,Oier Zarraga,ESP,MF,Udinese,Serie A,26,1999,6,1,182,2.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.500000,0.0,0.000000,0.000000,0.000000,0.000000,2.000000,3.500000,2.000000,0.000000,0.005000,0.500000,0.000000,0.0,0.49,0.00,0.00,0.0,27.5,0.000000,0.02,0.000000,0.000000,30.500000,36.000000,84.7,944,230,0.000000,0.000000,0.500000,3,0.000000,0.000000,34.500000,1.500000,1.000000,0.000000,0.0,2.000000,0.000000,0.500000,0.000000,0.0,0.0,0.000000,0.500000,1.500000,1.48,1.000000,0.000000,0.000000,0.500000,0.000000,0.000000,0.000000,0.00,1.000000,1.000000,0.500000,0.500000,0.000000,2.000000,0.0,2.000000,2.000000,0.500000,1.500000,1.000000,2.000000,3.000000,0.0,46.500000,3.000000,10.000000,27.000000,11.000000,0.500000,46.500000,1.000000,0.500000,50.0,0.500000,50.0,22.000000,258,149,4,0.500000,2.000000,1.000000,24.000000,30,18.4,90.0,0.500000,2.500000,18.0,2.500000,0.915000,0.000000,2.000000,-4,-1.98,-0.935000,0.700000,1.150000,-0.9,-0.46,0.0,2.000000,0.500000,0.000000,0.0,0.0,0.0,5.000000,2.000000,1.500000,57.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Oier Zarraga,100.0,NaN,Mediocentro,1.75,Derecho,30/06/2027,España,NaN,Udinese Calcio,2.0

In [ ]:
# prompt: ordenar df_merged por MatchScore, ascendente

df_merged = df_merged.sort_values(by='MatchScore', ascending=False)

In [ ]:
df_merged.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,G+A-PK,xG+xAG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,Dist,FK,npxG/Sh,G-xG,np:G-xG,Cmp,Att,Cmp%,TotDist,PrgDist,xA,A-xAG,KP,1/3,PPA,CrsPA,Live,Dead,FK_stats_passing_types,TB,Sw,Crs,TI,CK,In,Out,Str,Off,Blocks,SCA,SCA90,PassLive,PassDead,TO,Sh_stats_gca,Fld,Def,GCA,GCA90,Tkl,TklW,Def 3rd,Mid 3rd,Att 3rd,Att_stats_defense,Tkl%,Lost,Blocks_stats_defense,Sh_stats_defense,Pass,Int,Tkl+Int,Clr,Err,Touches,Def Pen,Def 3rd_stats_possession,Mid 3rd_stats_possession,Att 3rd_stats_possession,Att Pen,Live_stats_possession,Att_stats_possession,Succ,Succ%,Tkld,Tkld%,Carries,TotDist_stats_possession,PrgDist_stats_possession,1/3_stats_possession,CPA,Mis,Dis,Rec,Mn/MP,Min%,Mn/Start,Compl,Subs,Mn/Sub,unSub,PPM,onG,onGA,+/-,+/-90,On-Off,onxG,onxGA,xG+/-,xG+/-90,2CrdY,Fls,Fld_stats_misc,Off_stats_misc,PKwon,PKcon,OG,Recov,Won,Lost_stats_misc,Won%,MP_stats_keeper,Starts_stats_keeper,Min_stats_keeper,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm,FK_stats_keeper_adv,CK_stats_keeper_adv,OG_stats_keeper_adv,PSxG,PSxG/SoT,PSxG+/-,/90,Cmp_stats_keeper_adv,Att_stats_keeper_adv,Cmp%_stats_keeper_adv,Att (GK),Thr,Launch%,AvgLen,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist,MatchTransf,MatchScore,ScoreEquipo,Posicion,Altura,Pie,Contrato,Pais,Seg nacionalidad,equipo,Valor de mercado (M€)
1818,Himad Abdelli,ALG,MF,Angers,Ligue 1,26,1999,9,7,618,6.9,0.144928,0.000000,0.144928,0.0,0.144928,0.144928,0.000000,0.00000,0.159420,0.043478,0.043478,0.086957,3.623188,7.391304,1.594203,0.000000,0.030435,0.724638,0.144928,20.0,0.73,0.15,0.0,0.0,23.2,0.0,0.07,-0.014493,-0.043478,48.260870,56.376812,85.6,5631,1582,0.072464,-0.043478,0.724638,30,1.304348,0.000000,53.188406,3.188406,1.014493,0.434783,0.144928,1.159420,0.724638,0.724638,0.57971,0.144928,0.0,0.00000,0.579710,2.898551,2.91,2.028986,0.434783,0.289855,0.144928,0.000000,0.0,0.289855,0.29,1.739130,1.159420,0.869565,0.724638,0.144928,1.594203,81.8,0.289855,2.028986,0.434783,1.594203,1.159420,2.898551,0.869565,0.144928,68.840580,1.739130,17.681159,41.159420,11.159420,1.014493,68.695652,2.898551,1.304348,45.0,1.594203,55.0,36.956522,1507,928,21,0.000000,1.884058,1.159420,48.840580,69,57.2,81.0,0.434783,0.289855,25.0,0.000000,0.144928,1.014493,1.594203,-4,-0.58,-0.056522,1.043478,2.101449,-7.3,-1.07,0.00000,1.594203,0.724638,0.144928,0.0,0.000000,0.0,5.507246,0.869565,0.289855,75.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Himad Abdelli,100.0,NaN,Mediocentro ofensivo,1.85,Derecho,30/06/2026,Argelia,Francia,Angers SCO,7.0
1817,Ali Abdi,TUN,DF,Nice,Ligue 1,31,1993,5,5,300,3.3,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.606061,0.30303,0.000000,0.000000,0.121212,0.121212,1.818182,0.606061,3.333333,0.000000,0.036364,0.000000,0.000000,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.000000,0.000000,20.000000,26.969697,74.2,902,337,0.060606,-0.121212,1.212121,6,0.909091,0.303030,20.909091,6.060606,0.909091,0.000000,0.000000,1.515152,5.151515,0.000000,0.00000,0.000000,0.0,0.00000,1.818182,1.212121,1.27,1.212121,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00,2.121212,0.303030,1.515152,0.303030,0.303030,0.606061,0.0,0.606061,0.303030,0.000000,0.303030,0.909091,3.030303,2.121212,0.000000,38.181818,2.424242,11.818182,15.454545,11.212121,0.909091,38.181818,2.727273,0.909091,33.3,1.515152,55.6,17.272727,327,154,1,0.303030,2.424242,0.000000,19.696970,60,27.8,60.0,0.303030,0.000000,0.0,0.303030,0.303030,1.515152,0.606061,3,0.90,0.412121,0.757576,1.151515,-1.3,-0.40,0.30303,1.818182,1.818182,0.000000,0.0,0.000000,0.0,3.939394,0.909091,1.818182,33.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ali Abdi,100.0,NaN,Lateral izquierdo,1.83,Izquierdo,30/06/2027,Túnez,NaN,OGC Nice,3.0
1816,Salis Abdul Samed,GHA,MF,Nice,Ligue 1,25,2000,8,5,352,3.9,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.256410,0.00000,0.000000,0.000000,0.000000,0.000000,0.512821,1.025641,0.769231,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.000000,0.000000,37.179487,40.769231,91.2,1975,438,0.025641,0.000000,0.000000,8,0.000000,0.000000,39.743590,1.025641,1.025641,0.256410,0.000000,0.256410,0.000000,0.000000,0.00000,0.000000,0.0,0.00000,0.512821,0.512821,0.51,0.512821,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00,0.769231,0.256410,0.769231,0.000000,0.000000,0.769231,66.7,0.256410,0.512821,0.000000,0.512821,1.282051,2.051282,0.512821,0.000000,46.923077,1.538462,12.051282,30.256410,4.615385,0.512821,46.923077,0.769231,0.256410,33.3,0.512821,66.7,28.461538,529,217,2,0.256410,1.025641,1.025641,33.846154,44,32.6,62.0,0.000000,0.769231,14.0,1.025641,0.353846,1.794872,1.282051,2,0.51,0.225641,0.948718,1.538462,-2.2,-0.58,0.00000,1.282051,1.282051,0.000000,0.0,0.000000,0.0,2.820513,0.769231,0.769231,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Salis Abdul Samed,100.0,NaN,Pivote,1.79,Derecho,30/06/2028,Ghana,Costa de Marfil,OGC Nice,5.0
1815,Saud Abdulhamid,KSA,DF,Lens,Ligue 1,26,1999,9,1,204,2.3,0.000000,0.434783,0.434783,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.217391,0.217391,1.304348,5.652174,9.130435,0.191304,0.095652,0.434783,0.000000,0.0,0.44,0.00,0.0,0.0,11.7,0.0,0.05,0.000000,0.000000,46.956522,58.260870,80.6,1626,528,0.347826,0.217391,0.869565,4,1.304348,0.000000,50.434783,7.826087,0.000000,0.000000,0.000000,3.478261,7.826087,0.000000,0.00000,0.000000,0.0,0.00000,1.304348,1.739130,1.77,1.739130,0.000000,0.000000,0.000000,0.000000,0.0,0.434783,0.44,3.478261,1.739130,2.173913,0.869565,0.434783,4.347826,60.0,1.739130,1.739130,0.434783,1.304348,0.434783,3.913043,1.304348,0.000000,68.260870,2.173913,15.217391,24.347826,29.130435,3.043478,68.260870,2.173913,0.434783,20.0,1.304348,60.0,24.782609,237,127,0,0.434783,1.304348,0.434783,41.739130,23,18.9,90.0,0.434783,3.478261,14.0,0.869565,0.773913,1.304348,0.869565,1,0.44,-0.208696,2.043478,2.000000,0.2,0.07,0.00000,1.304348,0.869565,0.000000,0.0,0.434783,0.0,3.478261,0.869565,0.434783,66.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Saud Abdulhamid,100.0,NaN,Lateral derecho,1.75,Derecho,30/06/2026,Arabia Saudita,NaN,RC Lens,3.0
1814,Laurent Abergel,FRA,MF,Lorient,Ligue 1,32,1993,12,12,1036,11.5,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.347826,0.00000,0.043478,0.043478,0.043478,0.086957,1.130435,5.739130,1.043478,0.000000,0.007826,0.956522,0.173913,18.2,0.96,0.17,0.0,0.0,23.2,0.0,0.05,-0.043478,-0.043478,55.043478,63.130435,87.2,11873,3641,0.052174,-0.043478,0.695652,77,0.608696,0.086957,59.217391,3.652174,3.217391,0.086957,0.260870,0.173913,0.000000,0.000000,0.00000,0.000000,0.0,0.26087,0.608696,2.347826,2.35,2.000000,0.086957,0.000000,0.173913,0.086957,0.0,0.086957,0.09,1.739130,1.043478,0.782609,0.521739,0.434783,1.826087,42.9,1.043478,0.434783,0.000000,0.434783,0.695652,2.434783,1.826087,0.086957,70.434783,3.217391,18.956522,42.173913,9.826087,0.521739,70.434783,0.956522,0.347826,36.4,0.608696,63.6,45.826087,2155,1209,9,0.086957,0.608696,0.608696,52.608696,86,95.9,86.0,0.869565,0.000000,0.0,0.000000,0.072174,1.217391,2.173913,-11,-0.96,0.094783,1.304348,1.539130,-2.7,-0.23,0.00000,1.217391,0.869565,0.000000,0.0,0.086957,0.0,4.695652,0.695652,0.434783,61.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Laurent Abergel,100.0,NaN,Pivote,1.70,Derecho,30/06/2029,Francia,NaN,FC Lorient,2.5

In [ ]:
cols_tm_first = [
    "Player", "Pos", "Posicion", "Pais","Seg nacionalidad", "Age", "Born",
    "Altura", "Pie", "Contrato",
    "Squad", "Comp",
    "Valor de mercado (M€)",
]

# Añadir el resto manteniendo el orden actual
cols_rest = [col for col in df_merged.columns if col not in cols_tm_first]

df = df_merged[cols_tm_first + cols_rest]

In [ ]:
df.head()

,Player,Pos,Posicion,Pais,Seg nacionalidad,Age,Born,Altura,Pie,Contrato,Squad,Comp,Valor de mercado (M€),Nation,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,G+A-PK,xG+xAG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,Dist,FK,npxG/Sh,G-xG,np:G-xG,Cmp,Att,Cmp%,TotDist,PrgDist,xA,A-xAG,KP,1/3,PPA,CrsPA,Live,Dead,FK_stats_passing_types,TB,Sw,Crs,TI,CK,In,Out,Str,Off,Blocks,SCA,SCA90,PassLive,PassDead,TO,Sh_stats_gca,Fld,Def,GCA,GCA90,Tkl,TklW,Def 3rd,Mid 3rd,Att 3rd,Att_stats_defense,Tkl%,Lost,Blocks_stats_defense,Sh_stats_defense,Pass,Int,Tkl+Int,Clr,Err,Touches,Def Pen,Def 3rd_stats_possession,Mid 3rd_stats_possession,Att 3rd_stats_possession,Att Pen,Live_stats_possession,Att_stats_possession,Succ,Succ%,Tkld,Tkld%,Carries,TotDist_stats_possession,PrgDist_stats_possession,1/3_stats_possession,CPA,Mis,Dis,Rec,Mn/MP,Min%,Mn/Start,Compl,Subs,Mn/Sub,unSub,PPM,onG,onGA,+/-,+/-90,On-Off,onxG,onxGA,xG+/-,xG+/-90,2CrdY,Fls,Fld_stats_misc,Off_stats_misc,PKwon,PKcon,OG,Recov,Won,Lost_stats_misc,Won%,MP_stats_keeper,Starts_stats_keeper,Min_stats_keeper,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm,FK_stats_keeper_adv,CK_stats_keeper_adv,OG_stats_keeper_adv,PSxG,PSxG/SoT,PSxG+/-,/90,Cmp_stats_keeper_adv,Att_stats_keeper_adv,Cmp%_stats_keeper_adv,Att (GK),Thr,Launch%,AvgLen,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist,MatchTransf,MatchScore,ScoreEquipo,equipo
1818,Himad Abdelli,MF,Mediocentro ofensivo,Argelia,Francia,26,1999,1.85,Derecho,30/06/2026,Angers,Ligue 1,7.0,ALG,9,7,618,6.9,0.144928,0.000000,0.144928,0.0,0.144928,0.144928,0.000000,0.00000,0.159420,0.043478,0.043478,0.086957,3.623188,7.391304,1.594203,0.000000,0.030435,0.724638,0.144928,20.0,0.73,0.15,0.0,0.0,23.2,0.0,0.07,-0.014493,-0.043478,48.260870,56.376812,85.6,5631,1582,0.072464,-0.043478,0.724638,30,1.304348,0.000000,53.188406,3.188406,1.014493,0.434783,0.144928,1.159420,0.724638,0.724638,0.57971,0.144928,0.0,0.00000,0.579710,2.898551,2.91,2.028986,0.434783,0.289855,0.144928,0.000000,0.0,0.289855,0.29,1.739130,1.159420,0.869565,0.724638,0.144928,1.594203,81.8,0.289855,2.028986,0.434783,1.594203,1.159420,2.898551,0.869565,0.144928,68.840580,1.739130,17.681159,41.159420,11.159420,1.014493,68.695652,2.898551,1.304348,45.0,1.594203,55.0,36.956522,1507,928,21,0.000000,1.884058,1.159420,48.840580,69,57.2,81.0,0.434783,0.289855,25.0,0.000000,0.144928,1.014493,1.594203,-4,-0.58,-0.056522,1.043478,2.101449,-7.3,-1.07,0.00000,1.594203,0.724638,0.144928,0.0,0.000000,0.0,5.507246,0.869565,0.289855,75.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Himad Abdelli,100.0,NaN,Angers SCO
1817,Ali Abdi,DF,Lateral izquierdo,Túnez,NaN,31,1993,1.83,Izquierdo,30/06/2027,Nice,Ligue 1,3.0,TUN,5,5,300,3.3,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.606061,0.30303,0.000000,0.000000,0.121212,0.121212,1.818182,0.606061,3.333333,0.000000,0.036364,0.000000,0.000000,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.000000,0.000000,20.000000,26.969697,74.2,902,337,0.060606,-0.121212,1.212121,6,0.909091,0.303030,20.909091,6.060606,0.909091,0.000000,0.000000,1.515152,5.151515,0.000000,0.00000,0.000000,0.0,0.00000,1.818182,1.212121,1.27,1.212121,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00,2.121212,0.303030,1.515152,0.303030,0.303030,0.606061,0.0,0.606061,0.303030,0.000000,0.303030,0.909091,3.030303,2.121212,0.000000,38.181818,2.424242,11.818182,15.454545,11.212121,0.909091,38.181818,2.727273,0.909091,33.3,1.515152,55.6,17.272727,327,154,1,0.303030,2.424242,0.000000,19.696970,60,27.8,60.0,0.303030,0.000000,0.0,0.303030,0.303030,1.515152,0.606061,3,0.90,0.412121,0.757576,1.151515,-1.3,-0.40,0.30303,1.818182,1.818182,0.000000,0.0,0.000000,0.0,3.939394,0.909091,1.818182,33.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ali Abdi,100.0,NaN,OGC Nice
1816,Salis Abdul Samed,MF,Pivote,Ghana,Costa de Marfil,25,2000,1.79,Derecho,30/06/2028,Nice,Ligue 1,5.0,GHA,8,5,352,3.9,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.256410,0.00000,0.000000,0.000000,0.000000,0.000000,0.512821,1.025641,0.769231,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.000000,0.000000,37.179487,40.769231,91.2,1975,438,0.025641,0.000000,0.000000,8,0.000000,0.000000,39.743590,1.025641,1.025641,0.256410,0.000000,0.256410,0.000000,0.000000,0.00000,0.000000,0.0,0.00000,0.512821,0.512821,0.51,0.512821,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00,0.769231,0.256410,0.769231,0.000000,0.000000,0.769231,66.7,0.256410,0.512821,0.000000,0.512821,1.282051,2.051282,0.512821,0.000000,46.923077,1.538462,12.051282,30.256410,4.615385,0.512821,46.923077,0.769231,0.256410,33.3,0.512821,66.7,28.461538,529,217,2,0.256410,1.025641,1.025641,33.846154,44,32.6,62.0,0.000000,0.769231,14.0,1.025641,0.353846,1.794872,1.282051,2,0.51,0.225641,0.948718,1.538462,-2.2,-0.58,0.00000,1.282051,1.282051,0.000000,0.0,0.000000,0.0,2.820513,0.769231,0.769231,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Salis Abdul Samed,100.0,NaN,OGC Nice
1815,Saud Abdulhamid,DF,Lateral derecho,Arabia Saudita,NaN,26,1999,1.75,Derecho,30/06/2026,Lens,Ligue 1,3.0,KSA,9,1,204,2.3,0.000000,0.434783,0.434783,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.217391,0.217391,1.304348,5.652174,9.130435,0.191304,0.095652,0.434783,0.000000,0.0,0.44,0.00,0.0,0.0,11.7,0.0,0.05,0.000000,0.000000,46.956522,58.260870,80.6,1626,528,0.347826,0.217391,0.869565,4,1.304348,0.000000,50.434783,7.826087,0.000000,0.000000,0.000000,3.478261,7.826087,0.000000,0.00000,0.000000,0.0,0.00000,1.304348,1.739130,1.77,1.739130,0.000000,0.000000,0.000000,0.000000,0.0,0.434783,0.44,3.478261,1.739130,2.173913,0.869565,0.434783,4.347826,60.0,1.739130,1.739130,0.434783,1.304348,0.434783,3.913043,1.304348,0.000000,68.260870,2.173913,15.217391,24.347826,29.130435,3.043478,68.260870,2.173913,0.434783,20.0,1.304348,60.0,24.782609,237,127,0,0.434783,1.304348,0.434783,41.739130,23,18.9,90.0,0.434783,3.478261,14.0,0.869565,0.773913,1.304348,0.869565,1,0.44,-0.208696,2.043478,2.000000,0.2,0.07,0.00000,1.304348,0.869565,0.000000,0.0,0.434783,0.0,3.478261,0.869565,0.434783,66.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Saud Abdulhamid,100.0,NaN,RC Lens
1814,Laurent Abergel,MF,Pivote,Francia,NaN,32,1993,1.70,Derecho,30/06/2029,Lorient,Ligue 1,2.5,FRA,12,12,1036,11.5,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.347826,0.00000,0.043478,0.043478,0.043478,0.086957,1.130435,5.739130,1.043478,0.000000,0.007826,0.956522,0.173913,18.2,0.96,0.17,0.0,0.0,23.2,0.0,0.05,-0.043478,-0.043478,55.043478,63.130435,87.2,11873,3641,0.052174,-0.043478,0.695652,77,0.608696,0.086957,59.217391,3.652174,3.217391,0.086957,0.260870,0.173913,0.000000,0.000000,0.00000,0.000000,0.0,0.26087,0.608696,2.347826,2.35,2.000000,0.086957,0.000000,0.173913,0.086957,0.0,0.086957,0.09,1.739130,1.043478,0.782609,0.521739,0.434783,1.826087,42.9,1.043478,0.434783,0.000000,0.434783,0.695652,2.434783,1.826087,0.086957,70.434783,3.217391,18.956522,42.173913,9.826087,0.521739,70.434783,0.956522,0.347826,36.4,0.608696,63.6,45.826087,2155,1209,9,0.086957,0.608696,0.608696,52.608696,86,95.9,86.0,0.869565,0.000000,0.0,0.000000,0.072174,1.217391,2.173913,-11,-0.96,0.094783,1.304348,1.539130,-2.7,-0.23,0.00000,1.217391,0.869565,0.000000,0.0,0.086957,0.0,4.695652,0.695652,0.434783,61.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Laurent Abergel,100.0,NaN,FC Lorient

In [ ]:
df = df.drop(columns=["Nation"], errors="ignore")
df = df.drop(columns=["equipo"], errors="ignore")
df = df.drop(columns=["MatchScore"], errors="ignore")
df = df.drop(columns=["MatchTransf"], errors="ignore")
df = df.drop(columns=["MatchTransf"], errors="ignore")
df = df.drop(columns=["ScoreEquipo"], errors="ignore")

In [ ]:
df.head()

,Player,Pos,Posicion,Pais,Seg nacionalidad,Age,Born,Altura,Pie,Contrato,Squad,Comp,Valor de mercado (M€),MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,G+A-PK,xG+xAG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,Dist,FK,npxG/Sh,G-xG,np:G-xG,Cmp,Att,Cmp%,TotDist,PrgDist,xA,A-xAG,KP,1/3,PPA,CrsPA,Live,Dead,FK_stats_passing_types,TB,Sw,Crs,TI,CK,In,Out,Str,Off,Blocks,SCA,SCA90,PassLive,PassDead,TO,Sh_stats_gca,Fld,Def,GCA,GCA90,Tkl,TklW,Def 3rd,Mid 3rd,Att 3rd,Att_stats_defense,Tkl%,Lost,Blocks_stats_defense,Sh_stats_defense,Pass,Int,Tkl+Int,Clr,Err,Touches,Def Pen,Def 3rd_stats_possession,Mid 3rd_stats_possession,Att 3rd_stats_possession,Att Pen,Live_stats_possession,Att_stats_possession,Succ,Succ%,Tkld,Tkld%,Carries,TotDist_stats_possession,PrgDist_stats_possession,1/3_stats_possession,CPA,Mis,Dis,Rec,Mn/MP,Min%,Mn/Start,Compl,Subs,Mn/Sub,unSub,PPM,onG,onGA,+/-,+/-90,On-Off,onxG,onxGA,xG+/-,xG+/-90,2CrdY,Fls,Fld_stats_misc,Off_stats_misc,PKwon,PKcon,OG,Recov,Won,Lost_stats_misc,Won%,MP_stats_keeper,Starts_stats_keeper,Min_stats_keeper,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm,FK_stats_keeper_adv,CK_stats_keeper_adv,OG_stats_keeper_adv,PSxG,PSxG/SoT,PSxG+/-,/90,Cmp_stats_keeper_adv,Att_stats_keeper_adv,Cmp%_stats_keeper_adv,Att (GK),Thr,Launch%,AvgLen,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist
1818,Himad Abdelli,MF,Mediocentro ofensivo,Argelia,Francia,26,1999,1.85,Derecho,30/06/2026,Angers,Ligue 1,7.0,9,7,618,6.9,0.144928,0.000000,0.144928,0.0,0.144928,0.144928,0.000000,0.00000,0.159420,0.043478,0.043478,0.086957,3.623188,7.391304,1.594203,0.000000,0.030435,0.724638,0.144928,20.0,0.73,0.15,0.0,0.0,23.2,0.0,0.07,-0.014493,-0.043478,48.260870,56.376812,85.6,5631,1582,0.072464,-0.043478,0.724638,30,1.304348,0.000000,53.188406,3.188406,1.014493,0.434783,0.144928,1.159420,0.724638,0.724638,0.57971,0.144928,0.0,0.00000,0.579710,2.898551,2.91,2.028986,0.434783,0.289855,0.144928,0.000000,0.0,0.289855,0.29,1.739130,1.159420,0.869565,0.724638,0.144928,1.594203,81.8,0.289855,2.028986,0.434783,1.594203,1.159420,2.898551,0.869565,0.144928,68.840580,1.739130,17.681159,41.159420,11.159420,1.014493,68.695652,2.898551,1.304348,45.0,1.594203,55.0,36.956522,1507,928,21,0.000000,1.884058,1.159420,48.840580,69,57.2,81.0,0.434783,0.289855,25.0,0.000000,0.144928,1.014493,1.594203,-4,-0.58,-0.056522,1.043478,2.101449,-7.3,-1.07,0.00000,1.594203,0.724638,0.144928,0.0,0.000000,0.0,5.507246,0.869565,0.289855,75.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1817,Ali Abdi,DF,Lateral izquierdo,Túnez,NaN,31,1993,1.83,Izquierdo,30/06/2027,Nice,Ligue 1,3.0,5,5,300,3.3,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.606061,0.30303,0.000000,0.000000,0.121212,0.121212,1.818182,0.606061,3.333333,0.000000,0.036364,0.000000,0.000000,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.000000,0.000000,20.000000,26.969697,74.2,902,337,0.060606,-0.121212,1.212121,6,0.909091,0.303030,20.909091,6.060606,0.909091,0.000000,0.000000,1.515152,5.151515,0.000000,0.00000,0.000000,0.0,0.00000,1.818182,1.212121,1.27,1.212121,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00,2.121212,0.303030,1.515152,0.303030,0.303030,0.606061,0.0,0.606061,0.303030,0.000000,0.303030,0.909091,3.030303,2.121212,0.000000,38.181818,2.424242,11.818182,15.454545,11.212121,0.909091,38.181818,2.727273,0.909091,33.3,1.515152,55.6,17.272727,327,154,1,0.303030,2.424242,0.000000,19.696970,60,27.8,60.0,0.303030,0.000000,0.0,0.303030,0.303030,1.515152,0.606061,3,0.90,0.412121,0.757576,1.151515,-1.3,-0.40,0.30303,1.818182,1.818182,0.000000,0.0,0.000000,0.0,3.939394,0.909091,1.818182,33.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1816,Salis Abdul Samed,MF,Pivote,Ghana,Costa de Marfil,25,2000,1.79,Derecho,30/06/2028,Nice,Ligue 1,5.0,8,5,352,3.9,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.256410,0.00000,0.000000,0.000000,0.000000,0.000000,0.512821,1.025641,0.769231,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.000000,0.000000,37.179487,40.769231,91.2,1975,438,0.025641,0.000000,0.000000,8,0.000000,0.000000,39.743590,1.025641,1.025641,0.256410,0.000000,0.256410,0.000000,0.000000,0.00000,0.000000,0.0,0.00000,0.512821,0.512821,0.51,0.512821,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00,0.769231,0.256410,0.769231,0.000000,0.000000,0.769231,66.7,0.256410,0.512821,0.000000,0.512821,1.282051,2.051282,0.512821,0.000000,46.923077,1.538462,12.051282,30.256410,4.615385,0.512821,46.923077,0.769231,0.256410,33.3,0.512821,66.7,28.461538,529,217,2,0.256410,1.025641,1.025641,33.846154,44,32.6,62.0,0.000000,0.769231,14.0,1.025641,0.353846,1.794872,1.282051,2,0.51,0.225641,0.948718,1.538462,-2.2,-0.58,0.00000,1.282051,1.282051,0.000000,0.0,0.000000,0.0,2.820513,0.769231,0.769231,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1815,Saud Abdulhamid,DF,Lateral derecho,Arabia Saudita,NaN,26,1999,1.75,Derecho,30/06/2026,Lens,Ligue 1,3.0,9,1,204,2.3,0.000000,0.434783,0.434783,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.217391,0.217391,1.304348,5.652174,9.130435,0.191304,0.095652,0.434783,0.000000,0.0,0.44,0.00,0.0,0.0,11.7,0.0,0.05,0.000000,0.000000,46.956522,58.260870,80.6,1626,528,0.347826,0.217391,0.869565,4,1.304348,0.000000,50.434783,7.826087,0.000000,0.000000,0.000000,3.478261,7.826087,0.000000,0.00000,0.000000,0.0,0.00000,1.304348,1.739130,1.77,1.739130,0.000000,0.000000,0.000000,0.000000,0.0,0.434783,0.44,3.478261,1.739130,2.173913,0.869565,0.434783,4.347826,60.0,1.739130,1.739130,0.434783,1.304348,0.434783,3.913043,1.304348,0.000000,68.260870,2.173913,15.217391,24.347826,29.130435,3.043478,68.260870,2.173913,0.434783,20.0,1.304348,60.0,24.782609,237,127,0,0.434783,1.304348,0.434783,41.739130,23,18.9,90.0,0.434783,3.478261,14.0,0.869565,0.773913,1.304348,0.869565,1,0.44,-0.208696,2.043478,2.000000,0.2,0.07,0.00000,1.304348,0.869565,0.000000,0.0,0.434783,0.0,3.478261,0.869565,0.434783,66.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1814,Laurent Abergel,MF,Pivote,Francia,NaN,32,1993,1.70,Derecho,30/06/2029,Lorient,Ligue 1,2.5,12,12,1036,11.5,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.347826,0.00000,0.043478,0.043478,0.043478,0.086957,1.130435,5.739130,1.043478,0.000000,0.007826,0.956522,0.173913,18.2,0.96,0.17,0.0,0.0,23.2,0.0,0.05,-0.043478,-0.043478,55.043478,63.130435,87.2,11873,3641,0.052174,-0.043478,0.695652,77,0.608696,0.086957,59.217391,3.652174,3.217391,0.086957,0.260870,0.173913,0.000000,0.000000,0.00000,0.000000,0.0,0.26087,0.608696,2.347826,2.35,2.000000,0.086957,0.000000,0.173913,0.086957,0.0,0.086957,0.09,1.739130,1.043478,0.782609,0.521739,0.434783,1.826087,42.9,1.043478,0.434783,0.000000,0.434783,0.695652,2.434783,1.826087,0.086957,70.434783,3.217391,18.956522,42.173913,9.826087,0.521739,70.434783,0.956522,0.347826,36.4,0.608696,63.6,45.826087,2155,1209,9,0.086957,0.608696,0.608696,52.608696,86,95.9,86.0,0.869565,0.000000,0.0,0.000000,0.072174,1.217391,2.173913,-11,-0.96,0.094783,1.304348,1.539130,-2.7,-0.23,0.00000,1.217391,0.869565,0.000000,0.0,0.086957,0.0,4.695652,0.695652,0.434783,61.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df.to_csv('FBREF_TRANSF_NOV25.csv', index=False)

In [ ]:
df.shape

(2043, 180)